;;; fontaine-theme.el --- Dark on light theme -*-Emacs-Lisp-*-

;;         Copyright © 2016-2019  Tom Fontaine

;; Author: Tom Fontaine
;; Date:   19-Aug-2016

;; Permission is hereby granted, free of charge, to any person obtaining a
;; copy of this software and associated documentation files (the "Software",
;; to deal in the Software without restriction, including without limitation
;; the rights to use, copy, modify, merge, publish, distribute, sublicense,
;; and/or sell copies of the Software, and to permit persons to whom the
;; Software is furnished to do so, subject to the following conditions:

;; The above copyright notice and this permission notice shall be included in
;; all copies or substantial portions of the Software.

;; Except as contained in this notice, the name(s of the above copyright
;; holders shall not be used in advertising or otherwise to promote the sale,
;; use or other dealings in this Software without prior written authorization.

;; The software is provided "As Is", without warranty of any kind, express or
;; implied, including but not limited to the warranties of merchantability,
;; fitness for a particular purpose and noninfringement. In no event shall
;; the authors or copyright holders be liable for any claim, damages or other
;; liability, whether in an action of contract, tort or otherwise, arising
;; from, out of or in connection with the software or the use or other
;; dealings in the software.

;;; Commentary:

;; Revision:    16-Nov-2016 Added vhl/default-face
;;              04-Jan-2017 Added material colors
;;              05-Jan-2017 Converting from blue to Mint
;;              25-Apr-2017 Added flat  colors
;;              19-Jun-2018 Added multiple palettes
;;              02-Apr-2019 Changed font-family selection method
;;                          Added ‘Hack’ and made it the default font
;;                          Added ‘Source Code Pro’
;;              04-Apr-2019 Added ‘Cousine’
;;                          Added ‘CamingoCode’
;;                          Added ‘Fantasque’
;;              09-Jun-2019 Added ‘Nord’ colors
;;                          Added ‘Srcsery’ colors
;;              09-Jul-2019 Added ‘Victor’ font
;;              21-Jan-2020 Added ‘JetBrains’ font
;;              28-Jan-2020 Added ‘Iosevka’ and ‘IosevkaSlab’ font
;;

;;; Code:

(message "Loading fontaine-theme...")

(deftheme fontaine)

(add-to-list 'default-frame-alist '(alpha . (92 . 90)))

;; Windows fonts
;;   Consolas
;;   Office Code Pro
;;   Office Code Pro D
;;   Source Code Pro
;;   Cousine
;;   Fantasque
;;   Courier New

;;   Iosevka,Iosevka Light Extended:style=Light Extended,Regular

(let* ((font-family-list (font-family-list))

       (camingo         (car (member "CamingoCode"      font-family-list)))
       (consolas        (car (member "Consolas"         font-family-list)))
       (courier         (car (member "Courier 10 Pitch" font-family-list)))
       (cousine         (car (member "Cousine"          font-family-list)))
       (deja-vu         (car (member "DejaVu Sans Mono" font-family-list)))
       (fantasque       (car (member "Fantasque"        font-family-list)))
       (iosevka         (car (member "Iosevka"          font-family-list)))
       (iosevka-slab    (car (member "Iosevka Slab"     font-family-list)))
       (victor          (car (member "Victor"           font-family-list)))
       (hack            (car (member "Hack"             font-family-list)))
       (jet             (car (member "Jet"              font-family-list)))
       (source-code-pro (car (member "Source Code Pro"  font-family-list)))

       (font-family (or hack deja-vu consolas source-code-pro jet iosevka iosevka-slab cousine camingo fantasque victor courier))

       ;; named color definitions

       (american/light-greenish-blue "#55efc4")
       (american/faded-poster        "#81ecec")
       (american/green-darner-tail   "#74b9ff")
       (american/shy-moment          "#a29bfe")
       (american/city-lights         "#dfe6e9")
       (american/mint-leaf           "#00b894")
       (american/robins-egg-blue     "#00cec9")
       (american/electron-blue       "#0984e3")
       (american/exodus-fruit        "#6c5ce7")
       (american/soothing-breeze     "#b2bec3")
       (american/sour-lemon          "#ffeaa7")
       (american/first-date          "#fab1a0")
       (american/pink-glamour        "#ff7675")
       (american/pico-8-pink         "#fd79a8")
       (american/american-river      "#636e72")
       (american/bright-yarrow       "#fdcb6e")
       (american/orangeville         "#e17055")
       (american/chi-gong            "#d63031")
       (american/prunus-avium        "#e84393")
       (american/dracula-orchid      "#2d3436")

       (aussie/beekeeper        "#f6e58d")
       (aussie/spiced-nectarine "#ffbe76")
       (aussie/pink-glamour     "#ff7979")
       (aussie/june-bud         "#badc58")
       (aussie/coastal-breeze   "#dff9fb")
       (aussie/turbo            "#f9ca24")
       (aussie/quince-jelly     "#f0932b")
       (aussie/carmine-pink     "#eb4d4b")
       (aussie/pure-apple       "#6ab04c")
       (aussie/hint-of-ice-pack "#c7ecee")
       (aussie/middle-blue      "#7ed6df")
       (aussie/heliotrope       "#e056fd")
       (aussie/exodus-fruit     "#686de0")
       (aussie/deep-koamaru     "#30336b")
       (aussie/soaring-eagle    "#95afc0")
       (aussie/greenland-green  "#22a6b3")
       (aussie/steel-pink       "#be2edd")
       (aussie/blurple          "#4834d4")
       (aussie/deep-cove        "#130f40")
       (aussie/wizard-grey      "#535c68")

       (british/protoss-pylon          "#00a8ff")
       (british/periwinkle             "#9c88ff")
       (british/rise-n-shine           "#fbc531")
       (british/download-progress      "#4cd137")
       (british/seabrook               "#487eb0")
       (british/vanadyl-blue           "#0097e6")
       (british/matt-purple            "#8c7ae6")
       (british/nanohanacha-gold       "#e1b12c")
       (british/skirret-green          "#44bd32")
       (british/naval                  "#40739e")
       (british/nasturican-flower      "#e84118")
       (british/lynx-white             "#f5f6fa")
       (british/blueberry-soda         "#7f8fa6")
       (british/mazarine-blue          "#273c75")
       (british/blue-nights            "#353b48")
       (british/harley-davidson-orange "#c23616")
       (british/hint-of-pensive        "#dcdde1")
       (british/chain-gang-grey        "#718093")
       (british/pico-void              "#192a56")
       (british/electromagnetic        "#2f3640")

       (canadian/jigglypuff             "#ff9ff3")
       (canadian/casandora-yellow       "#feca57")
       (canadian/pastel-red             "#ff6b6b")
       (canadian/megaman                "#48dbfb")
       (canadian/wild-carribean-green   "#1dd1a1")
       (canadian/lián-hóng-lotus-pink   "#f368e0")
       (canadian/double-dragon-skin     "#ff9f43")
       (canadian/amour                  "#ee5253")
       (canadian/cyanite                "#0abde3")
       (canadian/dark-mountain-meadow   "#10ac84")
       (canadian/jade-dust              "#00d2d3")
       (canadian/joust-blue             "#54a0ff")
       (canadian/nasu-purple            "#5f27cd")
       (canadian/light-blue-ballerina   "#c8d6e5")
       (canadian/fuel-town              "#576574")
       (canadian/aqua-velvet            "#01a3a4")
       (canadian/bleu-de-france         "#2e86de")
       (canadian/bluebell               "#341f97")
       (canadian/storm-petrel           "#8395a7")
       (canadian/imperial-primer        "#222f3e")

       (chinese/golden-sand       "#eccc68")
       (chinese/coral             "#ff7f50")
       (chinese/wild-watermelon   "#ff6b81")
       (chinese/peace             "#a4b0be")
       (chinese/grisaille         "#57606f")
       (chinese/orange            "#ffa502")
       (chinese/bruschetta-tomato "#ff6348")
       (chinese/watermelon        "#ff4757")
       (chinese/baywharf          "#747d8c")
       (chinese/prestige-blue     "#2f3542")
       (chinese/lime-soap         "#7bed9f")
       (chinese/french-sky-blue   "#70a1ff")
       (chinese/saturated-sky     "#5352ed")
       (chinese/city-lights       "#dfe4ea")
       (chinese/ufo-green         "#2ed573")
       (chinese/clear-chill       "#1e90ff")
       (chinese/bright-greek      "#3742fa")
       (chinese/anti-flash-white  "#f1f2f6")
       (chinese/twinkle-blue      "#ced6e0")

       (color-blind/ultramarine-40 "#648fff")
       (color-blind/indigo-50      "#785ef0")
       (color-blind/magenta-50     "#dc267f")
       (color-blind/orange-40      "#fe6100")
       (color-blind/gold-20        "#ffb000")

       (dutch/sunflower                   "#ffc312")
       (dutch/energos                     "#c4e538")
       (dutch/blue-martina                "#12cbc4")
       (dutch/lavender-rose               "#fda7df")
       (dutch/bara-red                    "#ed4c67")
       (dutch/radiant-yellow              "#f79f1f")
       (dutch/android-green               "#a3cb38")
       (dutch/mediterranean-sea           "#1289a7")
       (dutch/lavender-tea                "#d980fa")
       (dutch/very-berry                  "#b53471")
       (dutch/puffins-bill                "#ee5a24")
       (dutch/pixelated-grass             "#009432")
       (dutch/merchant-marine-blue        "#0652dd")
       (dutch/forgotten-purple            "#9980fa")
       (dutch/hollyhock                   "#833471")
       (dutch/red-pigment                 "#ea2027")
       (dutch/turkish-aqua                "#006266")
       (dutch/20000-leagues-under-the-sea "#1b1464")
       (dutch/circumorbital-ring          "#5758bb")
       (dutch/magenta-purple              "#6f1e51")

       (flat/alizarin      "#e74c3c")
       (flat/amethyst      "#9b59b6")
       (flat/asbestos      "#7f8c8d")
       (flat/belize-hole   "#2980b9")
       (flat/carrot        "#e67e22")
       (flat/clouds        "#ecf0f1")
       (flat/concrete      "#95a5a6")
       (flat/emerald       "#2ecc71")
       (flat/green-sea     "#16a085")
       (flat/midnight-blue "#2c3e50")
       (flat/nephritis     "#27ae60")
       (flat/orange        "#f39c12")
       (flat/peter-river   "#3498db")
       (flat/pomegranate   "#c0392b")
       (flat/pumpkin       "#d35400")
       (flat/silver        "#bdc3c7")
       (flat/sunflower     "#f1c40f")
       (flat/turquoise     "#1abc9c")
       (flat/wet-asphalt   "#34495e")
       (flat/wisteria      "#8e44ad")

       (french/flat-flesh            "#fad390")
       (french/melon-melody          "#f8c291")
       (french/livid                 "#6a89cc")
       (french/spray                 "#82ccdd")
       (french/paradise-green        "#b8e994")
       (french/squash-blossom        "#f6b93b")
       (french/mandarin-red          "#e55039")
       (french/azraq-blue            "#4a69bd")
       (french/dupain                "#60a3bc")
       (french/aurora-green          "#78e08f")
       (french/iceland-poppy         "#fa983a")
       (french/tomato-red            "#eb2f06")
       (french/yuè-guāng-lán-blue    "#1e3799")
       (french/good-samaritan        "#3c6382")
       (french/waterfall             "#38ada9")
       (french/carrot-orange         "#e58e26")
       (french/jalapeno-red          "#b71540")
       (french/dark-sapphire         "#0c2461")
       (french/forest-blues          "#0a3d62")
       (french/reef-encounter        "#079992")

       (german/fusion-red      "#fc5c65")
       (german/orange-hibiscus "#fd9644")
       (german/flirtatious     "#fed330")
       (german/reptile-green   "#26de81")
       (german/maximum-blue    "#2bcbba")
       (german/desire          "#eb3b5a")
       (german/beniukon-bronze "#fa8231")
       (german/nyc-taxi        "#f7b731")
       (german/algal-fuel      "#20bf6b")
       (german/turquoise-topaz "#0fb9b1")
       (german/high-blue       "#45aaf2")
       (german/c64-ntsc        "#4b7bec")
       (german/lighter-purple  "#a55eea")
       (german/twinkle-blue    "#d1d8e0")
       (german/blue-grey       "#778ca3")
       (german/boyzone         "#2d98da")
       (german/royal-blue      "#3867d6")
       (german/gloomy-purple   "#8854d0")
       (german/innuendo        "#a5b1c2")
       (german/blue-horizon    "#4b6584")

       (ibm/aqua-01 "#d1f0f7")
       (ibm/aqua-10 "#a0e3f0")
       (ibm/aqua-20 "#71cddd")
       (ibm/aqua-30 "#00b6cb")
       (ibm/aqua-40 "#12a3b4")
       (ibm/aqua-50 "#188291")
       (ibm/aqua-60 "#17616b")
       (ibm/aqua-70 "#164d56")
       (ibm/aqua-80 "#13393e")
       (ibm/aqua-90 "#122a2e")

       (ibm/blue-01 "#e1ebf7")
       (ibm/blue-10 "#c8daf4")
       (ibm/blue-20 "#a8c0f3")
       (ibm/blue-30 "#79a6f6")
       (ibm/blue-40 "#5392ff")
       (ibm/blue-50 "#2d74da")
       (ibm/blue-60 "#1f57a4")
       (ibm/blue-70 "#25467a")
       (ibm/blue-80 "#1d3458")
       (ibm/blue-90 "#19273c")

       (ibm/cerulean-01 "#deedf7")
       (ibm/cerulean-10 "#c2dbf4")
       (ibm/cerulean-20 "#95c4f3")
       (ibm/cerulean-30 "#56acf2")
       (ibm/cerulean-40 "#009bef")
       (ibm/cerulean-50 "#047cc0")
       (ibm/cerulean-60 "#175d8d")
       (ibm/cerulean-70 "#1c496d")
       (ibm/cerulean-80 "#1d364d")
       (ibm/cerulean-90 "#1b2834")

       (ibm/cool-gray-01 "#e3ecec")
       (ibm/cool-gray-10 "#d0dada")
       (ibm/cool-gray-20 "#b8c1c1")
       (ibm/cool-gray-30 "#9fa7a7")
       (ibm/cool-gray-40 "#8c9696")
       (ibm/cool-gray-50 "#6f7878")
       (ibm/cool-gray-60 "#535a5a")
       (ibm/cool-gray-70 "#424747")
       (ibm/cool-gray-80 "#343334")
       (ibm/cool-gray-90 "#272727")

       (ibm/cool-white-1 "#fbfcfc")
       (ibm/cool-white-2 "#f8fafa")
       (ibm/cool-white-3 "#f4f7f7")
       (ibm/cool-white-4 "#f0f4f4")

       (ibm/gold-01 "#f5e8db")
       (ibm/gold-10 "#ffd191")
       (ibm/gold-20 "#ffb000")
       (ibm/gold-30 "#e39d14")
       (ibm/gold-40 "#c4881c")
       (ibm/gold-50 "#9c6d1e")
       (ibm/gold-60 "#74521b")
       (ibm/gold-70 "#5b421c")
       (ibm/gold-80 "#42301b")
       (ibm/gold-90 "#2f261c")

       (ibm/gray-01 "#eaeaea")
       (ibm/gray-10 "#d8d8d8")
       (ibm/gray-20 "#c0bfc0")
       (ibm/gray-30 "#a6a5a6")
       (ibm/gray-40 "#949394")
       (ibm/gray-50 "#777677")
       (ibm/gray-60 "#595859")
       (ibm/gray-70 "#464646")
       (ibm/gray-80 "#343334")
       (ibm/gray-90 "#272727")

       (ibm/green-01 "#cef3d1")
       (ibm/green-10 "#89eda0")
       (ibm/green-20 "#57d785")
       (ibm/green-30 "#34bc6e")
       (ibm/green-40 "#00aa5e")
       (ibm/green-50 "#00884b")
       (ibm/green-60 "#116639")
       (ibm/green-70 "#12512e")
       (ibm/green-80 "#123b22")
       (ibm/green-90 "#112c1b")

       (ibm/indigo-01 "#e9e8ff")
       (ibm/indigo-10 "#dcd4f7")
       (ibm/indigo-20 "#c7b6f7")
       (ibm/indigo-30 "#ae97f4")
       (ibm/indigo-40 "#9b82f3")
       (ibm/indigo-50 "#785ef0")
       (ibm/indigo-60 "#5a3ec8")
       (ibm/indigo-70 "#473793")
       (ibm/indigo-80 "#352969")
       (ibm/indigo-90 "#272149")

       (ibm/lime-01 "#d7f4bd")
       (ibm/lime-10 "#b4e876")
       (ibm/lime-20 "#95d13c")
       (ibm/lime-30 "#81b532")
       (ibm/lime-40 "#73a22c")
       (ibm/lime-50 "#5b8121")
       (ibm/lime-60 "#426200")
       (ibm/lime-70 "#374c1a")
       (ibm/lime-80 "#283912")
       (ibm/lime-90 "#1f2a10")

       (ibm/magenta-01 "#f5e7eb")
       (ibm/magenta-10 "#f5cedb")
       (ibm/magenta-20 "#f7aac3")
       (ibm/magenta-30 "#f87eac")
       (ibm/magenta-40 "#ff509e")
       (ibm/magenta-50 "#dc267f")
       (ibm/magenta-60 "#a91560")
       (ibm/magenta-70 "#831b4c")
       (ibm/magenta-80 "#5d1a38")
       (ibm/magenta-90 "#401a29")

       (ibm/neutral-white-1 "#fcfcfc")
       (ibm/neutral-white-2 "#f9f9f9")
       (ibm/neutral-white-3 "#f6f6f6")
       (ibm/neutral-white-4 "#f3f3f3")

       (ibm/orange-01 "#f5e8de")
       (ibm/orange-10 "#fdcfad")
       (ibm/orange-20 "#fcaf6d")
       (ibm/orange-30 "#fe8500")
       (ibm/orange-40 "#db7c00")
       (ibm/orange-50 "#ad6418")
       (ibm/orange-60 "#814b19")
       (ibm/orange-70 "#653d1b")
       (ibm/orange-80 "#482e1a")
       (ibm/orange-90 "#33241c")

       (ibm/peach-01 "#f7e7e2")
       (ibm/peach-10 "#f8d0c3")
       (ibm/peach-20 "#faad96")
       (ibm/peach-30 "#fc835c")
       (ibm/peach-40 "#fe6100")
       (ibm/peach-50 "#c45433")
       (ibm/peach-60 "#993a1d")
       (ibm/peach-70 "#782f1c")
       (ibm/peach-80 "#56251a")
       (ibm/peach-90 "#3a201b")

       (ibm/purple-01 "#f7e4fb")
       (ibm/purple-10 "#efcef3")
       (ibm/purple-20 "#e4adea")
       (ibm/purple-30 "#d68adf")
       (ibm/purple-40 "#cb71d7")
       (ibm/purple-50 "#c22dd5")
       (ibm/purple-60 "#9320a2")
       (ibm/purple-70 "#71237c")
       (ibm/purple-80 "#501e58")
       (ibm/purple-90 "#3b1a40")

       (ibm/red-01 "#f7e6e6")
       (ibm/red-10 "#fccec7")
       (ibm/red-20 "#ffaa9d")
       (ibm/red-30 "#ff806c")
       (ibm/red-40 "#ff5c49")
       (ibm/red-50 "#e62325")
       (ibm/red-60 "#aa231f")
       (ibm/red-70 "#83231e")
       (ibm/red-80 "#5c1f1b")
       (ibm/red-90 "#3e1d1b")

       (ibm/teal-01 "#c0f5e8")
       (ibm/teal-10 "#8ee9d4")
       (ibm/teal-20 "#40d5bb")
       (ibm/teal-30 "#00baa1")
       (ibm/teal-40 "#00a78f")
       (ibm/teal-50 "#008673")
       (ibm/teal-60 "#006456")
       (ibm/teal-70 "#124f44")
       (ibm/teal-80 "#133a32")
       (ibm/teal-90 "#122b26")

       (ibm/ultramarine-01 "#e7e9f7")
       (ibm/ultramarine-10 "#d1d7f4")
       (ibm/ultramarine-20 "#b0bef3")
       (ibm/ultramarine-30 "#89a2f6")
       (ibm/ultramarine-40 "#648fff")
       (ibm/ultramarine-50 "#3c6df0")
       (ibm/ultramarine-60 "#3151b7")
       (ibm/ultramarine-70 "#2e3f8f")
       (ibm/ultramarine-80 "#252e6a")
       (ibm/ultramarine-90 "#20214f")

       (ibm/violet-01 "#ece8f5")
       (ibm/violet-10 "#e2d2f4")
       (ibm/violet-20 "#d2b5f0")
       (ibm/violet-30 "#bf93eb")
       (ibm/violet-40 "#b07ce8")
       (ibm/violet-50 "#9753e1")
       (ibm/violet-60 "#7732bb")
       (ibm/violet-70 "#602797")
       (ibm/violet-80 "#44216a")
       (ibm/violet-90 "#321c4c")

       (ibm/warm-gray-01 "#efe9e9")
       (ibm/warm-gray-10 "#e2d5d5")
       (ibm/warm-gray-20 "#ccbcbc")
       (ibm/warm-gray-30 "#b4a1a1")
       (ibm/warm-gray-40 "#9e9191")
       (ibm/warm-gray-50 "#7d7373")
       (ibm/warm-gray-60 "#5f5757")
       (ibm/warm-gray-70 "#4b4545")
       (ibm/warm-gray-80 "#373232")
       (ibm/warm-gray-90 "#2a2626")

       (ibm/warm-white-1 "#fdfcfc")
       (ibm/warm-white-2 "#fbf8f8")
       (ibm/warm-white-3 "#f9f6f6")
       (ibm/warm-white-4 "#f6f3f3")

       (ibm/yellow-01 "#fbeaae")
       (ibm/yellow-10 "#fed500")
       (ibm/yellow-20 "#e3bc13")
       (ibm/yellow-30 "#c6a21a")
       (ibm/yellow-40 "#b3901f")
       (ibm/yellow-50 "#91721f")
       (ibm/yellow-60 "#70541b")
       (ibm/yellow-70 "#5b421a")
       (ibm/yellow-80 "#452f18")
       (ibm/yellow-90 "#372118")

       (indian/orchid-orange        "#fea47f")
       (indian/spiro-disco-ball     "#25ccf7")
       (indian/honey-glow           "#eab543")
       (indian/sweet-garden         "#55e6c1")
       (indian/falling-star         "#cad3c8")
       (indian/rich-gardenia        "#f97f51")
       (indian/clear-chill          "#1b9cfc")
       (indian/sarawak-white-pepper "#f8efba")
       (indian/keppel               "#58b19f")
       (indian/ships-officer        "#2c3a47")
       (indian/fiery-fuchsia        "#b33771")
       (indian/bluebell             "#3b3b98")
       (indian/georgia-peach        "#fd7272")
       (indian/oasis-stream         "#9aecdb")
       (indian/bright-ube           "#d6a2e8")
       (indian/magenta-purple       "#6d214f")
       (indian/ending-navy-blue     "#182c61")
       (indian/saquatch-socks       "#fc427b")
       (indian/pine-glade           "#bdc581")
       (indian/highlighter-lavender "#82589f")

       (material/bg-amber-050  "#fff8e1")
       (material/bg-amber-100  "#ffecb3")
       (material/bg-amber-200  "#ffe082")
       (material/bg-amber-300  "#ffd54f")
       (material/bg-amber-400  "#ffca28")
       (material/bg-amber-500  "#ffc107")
       (material/bg-amber-600  "#ffb300")
       (material/bg-amber-700  "#ffa000")
       (material/bg-amber-800  "#ff8f00")
       (material/bg-amber-900  "#ff6f00")
       (material/bg-amber-A100 "#ffe57f")
       (material/bg-amber-A200 "#ffd740")
       (material/bg-amber-A400 "#ffc400")
       (material/bg-amber-A700 "#ffab00")
       (material/bg-blue-100  "#bbdefb")
       (material/bg-blue-200  "#90caf9")
       (material/bg-blue-300  "#64b5f6")
       (material/bg-blue-400  "#42a5f5")
       (material/bg-blue-50   "#e3f2fd")
       (material/bg-blue-A100 "#82b1ff")
       (material/bg-blue-grey-050 "#eceff1")
       (material/bg-blue-grey-100 "#cfd8dc")
       (material/bg-blue-grey-200 "#b0bec5")
       (material/bg-blue-grey-300 "#90a4ae")
       (material/bg-brown-050 "#efebe9")
       (material/bg-brown-100 "#d7ccc8")
       (material/bg-brown-200 "#bcaaa4")
       (material/bg-cyan-050  "#e0f7fa")
       (material/bg-cyan-100  "#b2ebf2")
       (material/bg-cyan-200  "#80deea")
       (material/bg-cyan-300  "#4dd0e1")
       (material/bg-cyan-400  "#26c6da")
       (material/bg-cyan-500  "#00bcd4")
       (material/bg-cyan-600  "#00acc1")
       (material/bg-cyan-A100 "#84ffff")
       (material/bg-cyan-A200 "#18ffff")
       (material/bg-cyan-A400 "#00e5ff")
       (material/bg-cyan-A700 "#00b8d4")
       (material/bg-deep-orange-050  "#fbe9e7")
       (material/bg-deep-orange-100  "#ffccbc")
       (material/bg-deep-orange-200  "#ffab91")
       (material/bg-deep-orange-300  "#ff8a65")
       (material/bg-deep-orange-400  "#ff7043")
       (material/bg-deep-orange-A100 "#ff9e80")
       (material/bg-deep-orange-A200 "#ff6e40")
       (material/bg-deep-purple-050  "#ede7f6")
       (material/bg-deep-purple-100  "#d1c4e9")
       (material/bg-deep-purple-200  "#b39ddb")
       (material/bg-deep-purple-A100 "#b388ff")
       (material/bg-green-050  "#e8f5e9")
       (material/bg-green-100  "#c8e6c9")
       (material/bg-green-200  "#a5d6a7")
       (material/bg-green-300  "#81c784")
       (material/bg-green-400  "#66bb6a")
       (material/bg-green-500  "#4caf50")
       (material/bg-green-A100 "#b9f6ca")
       (material/bg-green-A200 "#69f0ae")
       (material/bg-green-A400 "#00e676")
       (material/bg-green-A700 "#00c853")
       (material/bg-grey-050 "#fafafa")
       (material/bg-grey-100 "#f5f5f5")
       (material/bg-grey-200 "#eeeeee")
       (material/bg-grey-300 "#e0e0e0")
       (material/bg-grey-400 "#bdbdbd")
       (material/bg-grey-500 "#9e9e9e")
       (material/bg-inidigo-050  "#e8eaf6")
       (material/bg-inidigo-100  "#c5cae9")
       (material/bg-inidigo-200  "#9fa8da")
       (material/bg-inidigo-A100 "#8c9eff")
       (material/bg-light-blue-050  "#e1f5fe")
       (material/bg-light-blue-100  "#b3e5fc")
       (material/bg-light-blue-200  "#81d4fa")
       (material/bg-light-blue-300  "#4fc3f7")
       (material/bg-light-blue-400  "#29b6f6")
       (material/bg-light-blue-500  "#03a9f4")
       (material/bg-light-blue-A100 "#80d8ff")
       (material/bg-light-blue-A200 "#40c4ff")
       (material/bg-light-blue-A400 "#00b0ff")
       (material/bg-light-green-050  "#f1f8e9")
       (material/bg-light-green-100  "#dcedc8")
       (material/bg-light-green-200  "#c5e1a5")
       (material/bg-light-green-300  "#aed581")
       (material/bg-light-green-400  "#9ccc65")
       (material/bg-light-green-500  "#8bc34a")
       (material/bg-light-green-600  "#7cb342")
       (material/bg-light-green-A100 "#ccff90")
       (material/bg-light-green-A200 "#b2ff59")
       (material/bg-light-green-A400 "#76ff03")
       (material/bg-light-green-A700 "#64dd17")
       (material/bg-lime-050  "#f9fbe7")
       (material/bg-lime-100  "#f0f4c3")
       (material/bg-lime-200  "#e6ee9c")
       (material/bg-lime-300  "#dce775")
       (material/bg-lime-400  "#d4e157")
       (material/bg-lime-500  "#cddc39")
       (material/bg-lime-600  "#c0ca33")
       (material/bg-lime-700  "#afb42b")
       (material/bg-lime-800  "#9e9d24")
       (material/bg-lime-A100 "#f4ff81")
       (material/bg-lime-A200 "#eeff41")
       (material/bg-lime-A400 "#c6ff00")
       (material/bg-lime-A700 "#aeea00")
       (material/bg-orange-050  "#fff3e0")
       (material/bg-orange-100  "#ffe0b2")
       (material/bg-orange-200  "#ffcc80")
       (material/bg-orange-300  "#ffb74d")
       (material/bg-orange-400  "#ffa726")
       (material/bg-orange-500  "#ff9800")
       (material/bg-orange-600  "#fb8c00")
       (material/bg-orange-700  "#f57c00")
       (material/bg-orange-A100 "#ffd180")
       (material/bg-orange-A200 "#ffab40")
       (material/bg-orange-A400 "#ff9100")
       (material/bg-orange-A700 "#ff6d00")
       (material/bg-pink-050  "#fce4ec")
       (material/bg-pink-100  "#f8bbd0")
       (material/bg-pink-200  "#f48fb1")
       (material/bg-pink-A100 "#ff80ab")
       (material/bg-purple-050 "#f3e5f5")
       (material/bg-purple-100 "#e1bee7")
       (material/bg-purple-200 "#ce93d8")
       (material/bg-purple-A100 "#ea80fc")
       (material/bg-red-050  "#ffebee")
       (material/bg-red-100  "#ffcdd2")
       (material/bg-red-200  "#ef9a9a")
       (material/bg-red-300  "#e57373")
       (material/bg-red-A100 "#ff8a80")
       (material/bg-teal-050  "#e0f2f1")
       (material/bg-teal-100  "#b2dfdb")
       (material/bg-teal-200  "#80cbc4")
       (material/bg-teal-300  "#4db6ac")
       (material/bg-teal-400  "#26a69a")
       (material/bg-teal-A100 "#a7ffeb")
       (material/bg-teal-A200 "#64ffda")
       (material/bg-teal-A400 "#1de9b6")
       (material/bg-teal-A700 "#00bfa5")
       (material/bg-yellow-050  "#fffde7")
       (material/bg-yellow-100  "#fff9c4")
       (material/bg-yellow-200  "#fff59d")
       (material/bg-yellow-300  "#fff176")
       (material/bg-yellow-400  "#ffee58")
       (material/bg-yellow-500  "#ffeb3b")
       (material/bg-yellow-600  "#fdd835")
       (material/bg-yellow-700  "#fbc02d")
       (material/bg-yellow-800  "#f9a825")
       (material/bg-yellow-900  "#f57f17")
       (material/bg-yellow-A100 "#ffff8d")
       (material/bg-yellow-A200 "#ffff00")
       (material/bg-yellow-A400 "#ffea00")
       (material/bg-yellow-A700 "#ffd600")
       (material/fg-blue-500  "#2196f3")
       (material/fg-blue-600  "#1e88e5")
       (material/fg-blue-700  "#1976d2")
       (material/fg-blue-800  "#1565c0")
       (material/fg-blue-900  "#0d47a1")
       (material/fg-blue-A200 "#448aff")
       (material/fg-blue-A400 "#2979ff")
       (material/fg-blue-A700 "#2962ff")
       (material/fg-blue-grey-400 "#78909c")
       (material/fg-blue-grey-500 "#607d8b")
       (material/fg-blue-grey-600 "#546e7a")
       (material/fg-blue-grey-700 "#455a64")
       (material/fg-blue-grey-800 "#37474f")
       (material/fg-blue-grey-900 "#263238")
       (material/fg-brown-300 "#a1887f")
       (material/fg-brown-400 "#8d6e63")
       (material/fg-brown-500 "#795548")
       (material/fg-brown-600 "#6d4c41")
       (material/fg-brown-700 "#5d4037")
       (material/fg-brown-800 "#4e342e")
       (material/fg-brown-900 "#3e2723")
       (material/fg-cyan-700  "#0097a7")
       (material/fg-cyan-800  "#00838f")
       (material/fg-cyan-900  "#006064")
       (material/fg-deep-orange-500  "#ff5722")
       (material/fg-deep-orange-600  "#f4511e")
       (material/fg-deep-orange-700  "#e64a19")
       (material/fg-deep-orange-800  "#d84315")
       (material/fg-deep-orange-900  "#bf360c")
       (material/fg-deep-orange-A400 "#ff3d00")
       (material/fg-deep-orange-A700 "#dd2c00")
       (material/fg-deep-purple-300  "#9575cd")
       (material/fg-deep-purple-400  "#7e57c2")
       (material/fg-deep-purple-500  "#673ab7")
       (material/fg-deep-purple-600  "#5e35b1")
       (material/fg-deep-purple-700  "#512da8")
       (material/fg-deep-purple-800  "#4527a0")
       (material/fg-deep-purple-900  "#311b92")
       (material/fg-deep-purple-A200 "#7c4dff")
       (material/fg-deep-purple-A400 "#651fff")
       (material/fg-deep-purple-A700 "#6200ea")
       (material/fg-green-600  "#43a047")
       (material/fg-green-700  "#388e3c")
       (material/fg-green-800  "#2e7d32")
       (material/fg-green-900  "#1b5e20")
       (material/fg-grey-600 "#757575")
       (material/fg-grey-700 "#616161")
       (material/fg-grey-800 "#424242")
       (material/fg-grey-900 "#212121")
       (material/fg-inidigo-300  "#7986cb")
       (material/fg-inidigo-400  "#5c6bc0")
       (material/fg-inidigo-500  "#3f51b5")
       (material/fg-inidigo-600  "#3949ab")
       (material/fg-inidigo-700  "#303f9f")
       (material/fg-inidigo-800  "#283593")
       (material/fg-inidigo-900  "#1a237e")
       (material/fg-inidigo-A200 "#536dfe")
       (material/fg-inidigo-A400 "#3d5afe")
       (material/fg-inidigo-A700 "#304ffe")
       (material/fg-light-blue-600  "#039be5")
       (material/fg-light-blue-700  "#0288d1")
       (material/fg-light-blue-800  "#0277bd")
       (material/fg-light-blue-900  "#01579b")
       (material/fg-light-blue-A700 "#0091ea")
       (material/fg-light-green-700  "#689f38")
       (material/fg-light-green-800  "#558b2f")
       (material/fg-light-green-900  "#33691e")
       (material/fg-lime-900  "#827717")
       (material/fg-orange-800  "#ef6c00")
       (material/fg-orange-900  "#e65100")
       (material/fg-pink-300  "#f06292")
       (material/fg-pink-400  "#ec407a")
       (material/fg-pink-500  "#e91e63")
       (material/fg-pink-600  "#d81b60")
       (material/fg-pink-700  "#c2185b")
       (material/fg-pink-800  "#ad1457")
       (material/fg-pink-900  "#880e4f")
       (material/fg-pink-A200 "#ff4081")
       (material/fg-pink-A400 "#f50057")
       (material/fg-pink-A700 "#c51162")
       (material/fg-purple-300 "#ba68c8")
       (material/fg-purple-400 "#ab47bc")
       (material/fg-purple-500 "#9c27b0")
       (material/fg-purple-600 "#8e24aa")
       (material/fg-purple-700 "#7b1fa2")
       (material/fg-purple-800 "#6a1b9a")
       (material/fg-purple-900 "#4a148c")
       (material/fg-purple-A200 "#e040fb")
       (material/fg-purple-A400 "#d500f9")
       (material/fg-purple-A700 "#aa00ff")
       (material/fg-red-400  "#ef5350")
       (material/fg-red-500  "#f44336")
       (material/fg-red-600  "#e53935")
       (material/fg-red-700  "#d32f2f")
       (material/fg-red-800  "#c62828")
       (material/fg-red-900  "#b71c1c")
       (material/fg-red-A200 "#ff5252")
       (material/fg-red-A400 "#ff1744")
       (material/fg-red-A700 "#d50000")
       (material/fg-teal-500  "#009688")
       (material/fg-teal-600  "#00897b")
       (material/fg-teal-700  "#00796b")
       (material/fg-teal-800  "#00695c")
       (material/fg-teal-900  "#004d40")

       (materialuicolors/red         "#f44336")
       (materialuicolors/pink        "#e91e63")
       (materialuicolors/purple      "#9c27b0")
       (materialuicolors/deep-purple "#673ab7")
       (materialuicolors/indigo      "#3f51b5")
       (materialuicolors/blue        "#2196f3")
       (materialuicolors/light-blue  "#03a9f4")
       (materialuicolors/cyan        "#00bcd4")
       (materialuicolors/teal        "#009688")
       (materialuicolors/green       "#4caf50")
       (materialuicolors/light-green "#8bc34a")
       (materialuicolors/lime        "#cddc39")
       (materialuicolors/yellow      "#ffeb3b")
       (materialuicolors/amber       "#ffc107")
       (materialuicolors/orange      "#ff9800")
       (materialuicolors/deep-orange "#ff5722")
       (materialuicolors/brown       "#795548")
       (materialuicolors/grey        "#9e9e9e")
       (materialuicolors/blue-grey   "#607d8b")

       (nord/polar-night-nord-0 "#2e3440")
       (nord/polar-night-nord-1 "#3b4252")
       (nord/polar-night-nord-2 "#434c5e")
       (nord/polar-night-nord-3 "#4c566a")
       (nord/snow-storm-nord-4  "#d8dee9")
       (nord/snow-storm-nord-5  "#d8dee9")
       (nord/snow-storm-nord-6  "#eceff4")
       (nord/frost-nord-7       "#8fbcbb")
       (nord/frost-nord-8       "#88c0d0")
       (nord/frost-nord-9       "#81a1c1")
       (nord/frost-nord-10      "#5e81ac")
       (nord/aurora-nord-11     "#bf616a")
       (nord/aurora-nord-12     "#d08770")
       (nord/aurora-nord-13     "#ebcb8b")
       (nord/aurora-nord-14     "#a3be8c")
       (nord/aurora-nord-15     "#b48ead")

       (qualitative/blue-40    "#5392ff")
       (qualitative/aqua-20    "#71cddd")
       (qualitative/green-30   "#34bc6e")
       (qualitative/lime-20    "#95d13c")
       (qualitative/gold-20    "#ffb000")
       (qualitative/peach-30   "#fe8500")
       (qualitative/magenta-40 "#ff509e")
       (qualitative/indigo-40  "#9b82f3")

       (russian/creamy-peach            "#f3a683")
       (russian/rosy-highlight          "#f7d794")
       (russian/soft-blue               "#778beb")
       (russian/brewed-mustard          "#e77f67")
       (russian/old-geranium            "#cf6a87")
       (russian/sawtooth-aak            "#f19066")
       (russian/summertime              "#f5cd79")
       (russian/cornflower              "#546de5")
       (russian/tigerlilly              "#e15f41")
       (russian/deep-rose               "#c44569")
       (russian/purple-mountain-majesty "#786fa6")
       (russian/rogue-pink              "#f8a5c2")
       (russian/squeaky                 "#63cdda")
       (russian/apple-valley            "#ea8685")
       (russian/pencil-lead             "#596275")
       (russian/purple-corallite        "#574b90")
       (russian/flamigo-pink            "#f78fb3")
       (russian/blue-curacao            "#3dc1d3")
       (russian/porcelain-rose          "#e66767")
       (russian/biscay                  "#303952")

       (spanish/jacksons-purple     "#40407a")
       (spanish/c64-purple          "#706fd3")
       (spanish/swan-white          "#f7f1e3")
       (spanish/summer-sky          "#34ace0")
       (spanish/celestial-green     "#33d9b2")
       (spanish/lucky-point         "#2c2c54")
       (spanish/liberty             "#474787")
       (spanish/hot-stone           "#aaa69d")
       (spanish/devil-blue          "#227093")
       (spanish/palm-springs-splash "#218c74")
       (spanish/fluorescent-red     "#ff5252")
       (spanish/synthetic-pumpkin   "#ff793f")
       (spanish/crocodile-tooth     "#d1ccc0")
       (spanish/mandarin-sorbet     "#ffb142")
       (spanish/spiced-butternut    "#ffda79")
       (spanish/eye-of-newt         "#b33939")
       (spanish/chilean-fire        "#cd6133")
       (spanish/grey-porcelain      "#84817a")
       (spanish/alameda-ochre       "#cc8e35")
       (spanish/desert              "#ccae62")

       (solar/bg-base0    "#839496")
       (solar/bg-base1    "#93a1a1")
       (solar/bg-base2    "#eee8d5")
       (solar/bg-base3    "#fdf6e3")
       (solar/fg-base00   "#657b83")
       (solar/fg-base01   "#586e75")
       (solar/fg-base02   "#073642")
       (solar/fg-base03   "#002b36")
       (solar/fg-blue     "#268bd2")
       (solar/fg-cyan     "#2aa198")
       (solar/fg-green    "#859900")
       (solar/fg-magenta  "#d33682")
       (solar/fg-orange   "#cb4b16")
       (solar/fg-red      "#dc322f")
       (solar/fg-violet   "#6c71c4")
       (solar/fg-yellow   "#b58900")

       (srcsery/black          "#1C1B19")
       (srcsery/red            "#EF2F27")
       (srcsery/green          "#519F50")
       (srcsery/yellow         "#FBB829")
       (srcsery/blue           "#2C78BF")
       (srcsery/magenta        "#E02C6D")
       (srcsery/cyan           "#0AAEB3")
       (srcsery/white          "#918175")
       (srcsery/bright-black   "#2D2C29")
       (srcsery/bright-red     "#F75341")
       (srcsery/bright-green   "#98BC37")
       (srcsery/bright-yellow  "#FED06E")
       (srcsery/bright-blue    "#68A8E4")
       (srcsery/bright-magenta "#FF5C8F")
       (srcsery/bright-cyan    "#53FDE9")
       (srcsery/bright-white   "#FCE8C3")

       (swedish/highlighter-pink     "#ef5777")
       (swedish/dark-periwinkle      "#575fcf")
       (swedish/megaman              "#4bcffa")
       (swedish/fresh-turquoise      "#34e7e4")
       (swedish/minty-green          "#0be881")
       (swedish/sizzling-red         "#f53b57")
       (swedish/free-speech-blue     "#3c40c6")
       (swedish/spiro-disco-ball     "#0fbcf9")
       (swedish/jade-dust            "#00d8d6")
       (swedish/green-teal           "#05c46b")
       (swedish/nârenji-orange       "#ffc048")
       (swedish/yriel-yellow         "#ffdd59")
       (swedish/sunset-orange        "#ff5e57")
       (swedish/hint-of-elusive-blue "#d2dae2")
       (swedish/good-night           "#485460")
       (swedish/chrome-yellow        "#ffa801")
       (swedish/vibrant-yellow       "#ffd32a")
       (swedish/red-orange           "#ff3f34")
       (swedish/london-square        "#808e9b")
       (swedish/black-pearl          "#1e272e")

       (turkish/bright-lilac     "#cd84f1")
       (turkish/pretty-please    "#ffcccc")
       (turkish/light-red        "#ff4d4d")
       (turkish/mandarin-sorbet  "#ffaf40")
       (turkish/unmellow-yellow  "#fffa65")
       (turkish/light-purple     "#c56cf0")
       (turkish/young-salmon     "#ffb8b8")
       (turkish/red-orange       "#ff3838")
       (turkish/radiant-yellow   "#ff9f1a")
       (turkish/dorn-yellow      "#fff200")
       (turkish/wintergreen      "#32ff7e")
       (turkish/electric-blue    "#7efff5")
       (turkish/neon-blue        "#18dcff")
       (turkish/light-slate-blue "#7d5fff")
       (turkish/shadowed-steel   "#4b4b4b")
       (turkish/weird-green      "#3ae374")
       (turkish/hammam-blue      "#67e6dc")
       (turkish/spiro-disco-ball "#17c0eb")
       (turkish/light-indigo     "#7158e2")
       (turkish/baltic-sea       "#3d3d3d")

       (x11/alice-blue             "#f0f8ff")
       (x11/antique-white          "#faebd7")
       (x11/antique-white1         "#ffefdb")
       (x11/antique-white2         "#eedfcc")
       (x11/antique-white3         "#cdc0b0")
       (x11/antique-white4         "#8b8378")
       (x11/aquamarine             "#7fffd4")
       (x11/aquamarine1            "#7fffd4")
       (x11/aquamarine2            "#76eec6")
       (x11/aquamarine3            "#66cdaa")
       (x11/aquamarine4            "#458b74")
       (x11/azure                  "#f0ffff")
       (x11/azure1                 "#f0ffff")
       (x11/azure2                 "#e0eeee")
       (x11/azure3                 "#c1cdcd")
       (x11/azure4                 "#838b8b")
       (x11/beige                  "#f5f5dc")
       (x11/bisque                 "#ffe4c4")
       (x11/bisque1                "#ffe4c4")
       (x11/bisque2                "#eed5b7")
       (x11/bisque3                "#cdb79e")
       (x11/bisque4                "#8b7d6b")
       (x11/black                  "#000000")
       (x11/blanched-almond        "#ffebcd")
       (x11/blue                   "#0000ff")
       (x11/blue-violet            "#8a2be2")
       (x11/blue1                  "#0000ff")
       (x11/blue2                  "#0000ee")
       (x11/blue3                  "#0000cd")
       (x11/blue4                  "#00008b")
       (x11/brown                  "#a52a2a")
       (x11/brown1                 "#ff4040")
       (x11/brown2                 "#ee3b3b")
       (x11/brown3                 "#cd3333")
       (x11/brown4                 "#8b2323")
       (x11/burlywood              "#deb887")
       (x11/burlywood1             "#ffd39b")
       (x11/burlywood2             "#eec591")
       (x11/burlywood3             "#cdaa7d")
       (x11/burlywood4             "#8b7355")
       (x11/cadet-blue             "#5f9ea0")
       (x11/cadet-blue1            "#98f5ff")
       (x11/cadet-blue2            "#8ee5ee")
       (x11/cadet-blue3            "#7ac5cd")
       (x11/cadet-blue4            "#53868b")
       (x11/chartreuse             "#7fff00")
       (x11/chartreuse1            "#7fff00")
       (x11/chartreuse2            "#76ee00")
       (x11/chartreuse3            "#66cd00")
       (x11/chartreuse4            "#458b00")
       (x11/chocolate              "#d2691e")
       (x11/chocolate1             "#ff7f24")
       (x11/chocolate2             "#ee7621")
       (x11/chocolate3             "#cd661d")
       (x11/chocolate4             "#8b4513")
       (x11/coral                  "#ff7f50")
       (x11/coral1                 "#ff7256")
       (x11/coral2                 "#ee6a50")
       (x11/coral3                 "#cd5b45")
       (x11/coral4                 "#8b3e2f")
       (x11/cornflower-blue        "#6495ed")
       (x11/cornsilk               "#fff8dc")
       (x11/cornsilk1              "#fff8dc")
       (x11/cornsilk2              "#eee8cd")
       (x11/cornsilk3              "#cdc8b1")
       (x11/cornsilk4              "#8b8878")
       (x11/cyan                   "#00ffff")
       (x11/cyan1                  "#00ffff")
       (x11/cyan2                  "#00eeee")
       (x11/cyan3                  "#00cdcd")
       (x11/cyan4                  "#008b8b")
       (x11/dark-blue              "#00008b")
       (x11/dark-cyan              "#008b8b")
       (x11/dark-goldenrod         "#b8860b")
       (x11/dark-goldenrod1        "#ffb90f")
       (x11/dark-goldenrod2        "#eead0e")
       (x11/dark-goldenrod3        "#cd950c")
       (x11/dark-goldenrod4        "#8b6508")
       (x11/dark-gray              "#a9a9a9")
       (x11/dark-green             "#006400")
       (x11/dark-grey              "#a9a9a9")
       (x11/dark-khaki             "#bdb76b")
       (x11/dark-magenta           "#8b008b")
       (x11/dark-olive-green       "#556b2f")
       (x11/dark-olive-green1      "#caff70")
       (x11/dark-olive-green2      "#bcee68")
       (x11/dark-olive-green3      "#a2cd5a")
       (x11/dark-olive-green4      "#6e8b3d")
       (x11/dark-orange            "#ff8c00")
       (x11/dark-orange1           "#ff7f00")
       (x11/dark-orange2           "#ee7600")
       (x11/dark-orange3           "#cd6600")
       (x11/dark-orange4           "#8b4500")
       (x11/dark-orchid            "#9932cc")
       (x11/dark-orchid1           "#bf3eff")
       (x11/dark-orchid2           "#b23aee")
       (x11/dark-orchid3           "#9a32cd")
       (x11/dark-orchid4           "#68228b")
       (x11/dark-red               "#8b0000")
       (x11/dark-salmon            "#e9967a")
       (x11/dark-sea-green         "#8fbc8f")
       (x11/dark-sea-green1        "#c1ffc1")
       (x11/dark-sea-green2        "#b4eeb4")
       (x11/dark-sea-green3        "#9bcd9b")
       (x11/dark-sea-green4        "#698b69")
       (x11/dark-slate-blue        "#483d8b")
       (x11/dark-slate-gray        "#2f4f4f")
       (x11/dark-slate-gray1       "#97ffff")
       (x11/dark-slate-gray2       "#8deeee")
       (x11/dark-slate-gray3       "#79cdcd")
       (x11/dark-slate-gray4       "#528b8b")
       (x11/dark-slate-grey        "#2f4f4f")
       (x11/dark-turquoise         "#00ced1")
       (x11/dark-violet            "#9400d3")
       (x11/debian-red             "#d70751")
       (x11/deep-pink              "#ff1493")
       (x11/deep-pink1             "#ff1493")
       (x11/deep-pink2             "#ee1289")
       (x11/deep-pink3             "#cd1076")
       (x11/deep-pink4             "#8b0a50")
       (x11/deep-sky-blue          "#00bfff")
       (x11/deep-sky-blue1         "#00bfff")
       (x11/deep-sky-blue2         "#00b2ee")
       (x11/deep-sky-blue3         "#009acd")
       (x11/deep-sky-blue4         "#00688b")
       (x11/dim-gray               "#696969")
       (x11/dim-grey               "#696969")
       (x11/dodger-blue            "#1e90ff")
       (x11/dodger-blue1           "#1e90ff")
       (x11/dodger-blue2           "#1c86ee")
       (x11/dodger-blue3           "#1874cd")
       (x11/dodger-blue4           "#104e8b")
       (x11/firebrick              "#b22222")
       (x11/firebrick1             "#ff3030")
       (x11/firebrick2             "#ee2c2c")
       (x11/firebrick3             "#cd2626")
       (x11/firebrick4             "#8b1a1a")
       (x11/floral-white           "#fffaf0")
       (x11/forest-green           "#228b22")
       (x11/gainsboro              "#dcdcdc")
       (x11/ghost-white            "#f8f8ff")
       (x11/gold                   "#ffd700")
       (x11/gold1                  "#ffd700")
       (x11/gold2                  "#eec900")
       (x11/gold3                  "#cdad00")
       (x11/gold4                  "#8b7500")
       (x11/goldenrod              "#daa520")
       (x11/goldenrod1             "#ffc125")
       (x11/goldenrod2             "#eeb422")
       (x11/goldenrod3             "#cd9b1d")
       (x11/goldenrod4             "#8b6914")
       (x11/gray                   "#bebebe")
       (x11/gray0                  "#000000")
       (x11/gray1                  "#030303")
       (x11/gray10                 "#1a1a1a")
       (x11/gray100                "#ffffff")
       (x11/gray11                 "#1c1c1c")
       (x11/gray12                 "#1f1f1f")
       (x11/gray13                 "#212121")
       (x11/gray14                 "#242424")
       (x11/gray15                 "#262626")
       (x11/gray16                 "#292929")
       (x11/gray17                 "#2b2b2b")
       (x11/gray18                 "#2e2e2e")
       (x11/gray19                 "#303030")
       (x11/gray2                  "#050505")
       (x11/gray20                 "#333333")
       (x11/gray21                 "#363636")
       (x11/gray22                 "#383838")
       (x11/gray23                 "#3b3b3b")
       (x11/gray24                 "#3d3d3d")
       (x11/gray25                 "#404040")
       (x11/gray26                 "#424242")
       (x11/gray27                 "#454545")
       (x11/gray28                 "#474747")
       (x11/gray29                 "#4a4a4a")
       (x11/gray3                  "#080808")
       (x11/gray30                 "#4d4d4d")
       (x11/gray31                 "#4f4f4f")
       (x11/gray32                 "#525252")
       (x11/gray33                 "#545454")
       (x11/gray34                 "#575757")
       (x11/gray35                 "#595959")
       (x11/gray36                 "#5c5c5c")
       (x11/gray37                 "#5e5e5e")
       (x11/gray38                 "#616161")
       (x11/gray39                 "#636363")
       (x11/gray4                  "#0a0a0a")
       (x11/gray40                 "#666666")
       (x11/gray41                 "#696969")
       (x11/gray42                 "#6b6b6b")
       (x11/gray43                 "#6e6e6e")
       (x11/gray44                 "#707070")
       (x11/gray45                 "#737373")
       (x11/gray46                 "#757575")
       (x11/gray47                 "#787878")
       (x11/gray48                 "#7a7a7a")
       (x11/gray49                 "#7d7d7d")
       (x11/gray5                  "#0d0d0d")
       (x11/gray50                 "#7f7f7f")
       (x11/gray51                 "#828282")
       (x11/gray52                 "#858585")
       (x11/gray53                 "#878787")
       (x11/gray54                 "#8a8a8a")
       (x11/gray55                 "#8c8c8c")
       (x11/gray56                 "#8f8f8f")
       (x11/gray57                 "#919191")
       (x11/gray58                 "#949494")
       (x11/gray59                 "#969696")
       (x11/gray6                  "#0f0f0f")
       (x11/gray60                 "#999999")
       (x11/gray61                 "#9c9c9c")
       (x11/gray62                 "#9e9e9e")
       (x11/gray63                 "#a1a1a1")
       (x11/gray64                 "#a3a3a3")
       (x11/gray65                 "#a6a6a6")
       (x11/gray66                 "#a8a8a8")
       (x11/gray67                 "#ababab")
       (x11/gray68                 "#adadad")
       (x11/gray69                 "#b0b0b0")
       (x11/gray7                  "#121212")
       (x11/gray70                 "#b3b3b3")
       (x11/gray71                 "#b5b5b5")
       (x11/gray72                 "#b8b8b8")
       (x11/gray73                 "#bababa")
       (x11/gray74                 "#bdbdbd")
       (x11/gray75                 "#bfbfbf")
       (x11/gray76                 "#c2c2c2")
       (x11/gray77                 "#c4c4c4")
       (x11/gray78                 "#c7c7c7")
       (x11/gray79                 "#c9c9c9")
       (x11/gray8                  "#141414")
       (x11/gray80                 "#cccccc")
       (x11/gray81                 "#cfcfcf")
       (x11/gray82                 "#d1d1d1")
       (x11/gray83                 "#d4d4d4")
       (x11/gray84                 "#d6d6d6")
       (x11/gray85                 "#d9d9d9")
       (x11/gray86                 "#dbdbdb")
       (x11/gray87                 "#dedede")
       (x11/gray88                 "#e0e0e0")
       (x11/gray89                 "#e3e3e3")
       (x11/gray9                  "#171717")
       (x11/gray90                 "#e5e5e5")
       (x11/gray91                 "#e8e8e8")
       (x11/gray92                 "#ebebeb")
       (x11/gray93                 "#ededed")
       (x11/gray94                 "#f0f0f0")
       (x11/gray95                 "#f2f2f2")
       (x11/gray96                 "#f5f5f5")
       (x11/gray97                 "#f7f7f7")
       (x11/gray98                 "#fafafa")
       (x11/gray99                 "#fcfcfc")
       (x11/green                  "#00ff00")
       (x11/green-yellow           "#adff2f")
       (x11/green1                 "#00ff00")
       (x11/green2                 "#00ee00")
       (x11/green3                 "#00cd00")
       (x11/green4                 "#008b00")
       (x11/grey                   "#bebebe")
       (x11/grey0                  "#000000")
       (x11/grey1                  "#030303")
       (x11/grey10                 "#1a1a1a")
       (x11/grey100                "#ffffff")
       (x11/grey11                 "#1c1c1c")
       (x11/grey12                 "#1f1f1f")
       (x11/grey13                 "#212121")
       (x11/grey14                 "#242424")
       (x11/grey15                 "#262626")
       (x11/grey16                 "#292929")
       (x11/grey17                 "#2b2b2b")
       (x11/grey18                 "#2e2e2e")
       (x11/grey19                 "#303030")
       (x11/grey2                  "#050505")
       (x11/grey20                 "#333333")
       (x11/grey21                 "#363636")
       (x11/grey22                 "#383838")
       (x11/grey23                 "#3b3b3b")
       (x11/grey24                 "#3d3d3d")
       (x11/grey25                 "#404040")
       (x11/grey26                 "#424242")
       (x11/grey27                 "#454545")
       (x11/grey28                 "#474747")
       (x11/grey29                 "#4a4a4a")
       (x11/grey3                  "#080808")
       (x11/grey30                 "#4d4d4d")
       (x11/grey31                 "#4f4f4f")
       (x11/grey32                 "#525252")
       (x11/grey33                 "#545454")
       (x11/grey34                 "#575757")
       (x11/grey35                 "#595959")
       (x11/grey36                 "#5c5c5c")
       (x11/grey37                 "#5e5e5e")
       (x11/grey38                 "#616161")
       (x11/grey39                 "#636363")
       (x11/grey4                  "#0a0a0a")
       (x11/grey40                 "#666666")
       (x11/grey41                 "#696969")
       (x11/grey42                 "#6b6b6b")
       (x11/grey43                 "#6e6e6e")
       (x11/grey44                 "#707070")
       (x11/grey45                 "#737373")
       (x11/grey46                 "#757575")
       (x11/grey47                 "#787878")
       (x11/grey48                 "#7a7a7a")
       (x11/grey49                 "#7d7d7d")
       (x11/grey5                  "#0d0d0d")
       (x11/grey50                 "#7f7f7f")
       (x11/grey51                 "#828282")
       (x11/grey52                 "#858585")
       (x11/grey53                 "#878787")
       (x11/grey54                 "#8a8a8a")
       (x11/grey55                 "#8c8c8c")
       (x11/grey56                 "#8f8f8f")
       (x11/grey57                 "#919191")
       (x11/grey58                 "#949494")
       (x11/grey59                 "#969696")
       (x11/grey6                  "#0f0f0f")
       (x11/grey60                 "#999999")
       (x11/grey61                 "#9c9c9c")
       (x11/grey62                 "#9e9e9e")
       (x11/grey63                 "#a1a1a1")
       (x11/grey64                 "#a3a3a3")
       (x11/grey65                 "#a6a6a6")
       (x11/grey66                 "#a8a8a8")
       (x11/grey67                 "#ababab")
       (x11/grey68                 "#adadad")
       (x11/grey69                 "#b0b0b0")
       (x11/grey7                  "#121212")
       (x11/grey70                 "#b3b3b3")
       (x11/grey71                 "#b5b5b5")
       (x11/grey72                 "#b8b8b8")
       (x11/grey73                 "#bababa")
       (x11/grey74                 "#bdbdbd")
       (x11/grey75                 "#bfbfbf")
       (x11/grey76                 "#c2c2c2")
       (x11/grey77                 "#c4c4c4")
       (x11/grey78                 "#c7c7c7")
       (x11/grey79                 "#c9c9c9")
       (x11/grey8                  "#141414")
       (x11/grey80                 "#cccccc")
       (x11/grey81                 "#cfcfcf")
       (x11/grey82                 "#d1d1d1")
       (x11/grey83                 "#d4d4d4")
       (x11/grey84                 "#d6d6d6")
       (x11/grey85                 "#d9d9d9")
       (x11/grey86                 "#dbdbdb")
       (x11/grey87                 "#dedede")
       (x11/grey88                 "#e0e0e0")
       (x11/grey89                 "#e3e3e3")
       (x11/grey9                  "#171717")
       (x11/grey90                 "#e5e5e5")
       (x11/grey91                 "#e8e8e8")
       (x11/grey92                 "#ebebeb")
       (x11/grey93                 "#ededed")
       (x11/grey94                 "#f0f0f0")
       (x11/grey95                 "#f2f2f2")
       (x11/grey96                 "#f5f5f5")
       (x11/grey97                 "#f7f7f7")
       (x11/grey98                 "#fafafa")
       (x11/grey99                 "#fcfcfc")
       (x11/honeydew               "#f0fff0")
       (x11/honeydew1              "#f0fff0")
       (x11/honeydew2              "#e0eee0")
       (x11/honeydew3              "#c1cdc1")
       (x11/honeydew4              "#838b83")
       (x11/hot-pink               "#ff69b4")
       (x11/hot-pink1              "#ff6eb4")
       (x11/hot-pink2              "#ee6aa7")
       (x11/hot-pink3              "#cd6090")
       (x11/hot-pink4              "#8b3a62")
       (x11/indian-red             "#cd5c5c")
       (x11/indian-red1            "#ff6a6a")
       (x11/indian-red2            "#ee6363")
       (x11/indian-red3            "#cd5555")
       (x11/indian-red4            "#8b3a3a")
       (x11/ivory                  "#fffff0")
       (x11/ivory1                 "#fffff0")
       (x11/ivory2                 "#eeeee0")
       (x11/ivory3                 "#cdcdc1")
       (x11/ivory4                 "#8b8b83")
       (x11/khaki                  "#f0e68c")
       (x11/khaki1                 "#fff68f")
       (x11/khaki2                 "#eee685")
       (x11/khaki3                 "#cdc673")
       (x11/khaki4                 "#8b864e")
       (x11/lavender               "#e6e6fa")
       (x11/lavender-blush         "#fff0f5")
       (x11/lavender-blush1        "#fff0f5")
       (x11/lavender-blush2        "#eee0e5")
       (x11/lavender-blush3        "#cdc1c5")
       (x11/lavender-blush4        "#8b8386")
       (x11/lawn-green             "#7cfc00")
       (x11/lemon-chiffon          "#fffacd")
       (x11/lemon-chiffon1         "#fffacd")
       (x11/lemon-chiffon2         "#eee9bf")
       (x11/lemon-chiffon3         "#cdc9a5")
       (x11/lemon-chiffon4         "#8b8970")
       (x11/light-blue             "#add8e6")
       (x11/light-blue1            "#bfefff")
       (x11/light-blue2            "#b2dfee")
       (x11/light-blue3            "#9ac0cd")
       (x11/light-blue4            "#68838b")
       (x11/light-coral            "#f08080")
       (x11/light-cyan             "#e0ffff")
       (x11/light-cyan1            "#e0ffff")
       (x11/light-cyan2            "#d1eeee")
       (x11/light-cyan3            "#b4cdcd")
       (x11/light-cyan4            "#7a8b8b")
       (x11/light-goldenrod        "#eedd82")
       (x11/light-goldenrod-yellow "#fafad2")
       (x11/light-goldenrod1       "#ffec8b")
       (x11/light-goldenrod2       "#eedc82")
       (x11/light-goldenrod3       "#cdbe70")
       (x11/light-goldenrod4       "#8b814c")
       (x11/light-gray             "#d3d3d3")
       (x11/light-green            "#90ee90")
       (x11/light-grey             "#d3d3d3")
       (x11/light-pink             "#ffb6c1")
       (x11/light-pink1            "#ffaeb9")
       (x11/light-pink2            "#eea2ad")
       (x11/light-pink3            "#cd8c95")
       (x11/light-pink4            "#8b5f65")
       (x11/light-salmon           "#ffa07a")
       (x11/light-salmon1          "#ffa07a")
       (x11/light-salmon2          "#ee9572")
       (x11/light-salmon3          "#cd8162")
       (x11/light-salmon4          "#8b5742")
       (x11/light-sea-green        "#20b2aa")
       (x11/light-sky-blue         "#87cefa")
       (x11/light-sky-blue1        "#b0e2ff")
       (x11/light-sky-blue2        "#a4d3ee")
       (x11/light-sky-blue3        "#8db6cd")
       (x11/light-sky-blue4        "#607b8b")
       (x11/light-slate-blue       "#8470ff")
       (x11/light-slate-gray       "#778899")
       (x11/light-slate-grey       "#778899")
       (x11/light-steel-blue       "#b0c4de")
       (x11/light-steel-blue1      "#cae1ff")
       (x11/light-steel-blue2      "#bcd2ee")
       (x11/light-steel-blue3      "#a2b5cd")
       (x11/light-steel-blue4      "#6e7b8b")
       (x11/light-yellow           "#ffffe0")
       (x11/light-yellow1          "#ffffe0")
       (x11/light-yellow2          "#eeeed1")
       (x11/light-yellow3          "#cdcdb4")
       (x11/light-yellow4          "#8b8b7a")
       (x11/lime-green             "#32cd32")
       (x11/linen                  "#faf0e6")
       (x11/magenta                "#ff00ff")
       (x11/magenta1               "#ff00ff")
       (x11/magenta2               "#ee00ee")
       (x11/magenta3               "#cd00cd")
       (x11/magenta4               "#8b008b")
       (x11/maroon                 "#b03060")
       (x11/maroon1                "#ff34b3")
       (x11/maroon2                "#ee30a7")
       (x11/maroon3                "#cd2990")
       (x11/maroon4                "#8b1c62")
       (x11/medium-aquamarine      "#66cdaa")
       (x11/medium-blue            "#0000cd")
       (x11/medium-orchid          "#ba55d3")
       (x11/medium-orchid1         "#e066ff")
       (x11/medium-orchid2         "#d15fee")
       (x11/medium-orchid3         "#b452cd")
       (x11/medium-orchid4         "#7a378b")
       (x11/medium-purple          "#9370db")
       (x11/medium-purple1         "#ab82ff")
       (x11/medium-purple2         "#9f79ee")
       (x11/medium-purple3         "#8968cd")
       (x11/medium-purple4         "#5d478b")
       (x11/medium-sea-green       "#3cb371")
       (x11/medium-slate-blue      "#7b68ee")
       (x11/medium-spring-green    "#00fa9a")
       (x11/medium-turquoise       "#48d1cc")
       (x11/medium-violet-red      "#c71585")
       (x11/midnight-blue          "#191970")
       (x11/mint-cream             "#f5fffa")
       (x11/misty-rose             "#ffe4e1")
       (x11/misty-rose1            "#ffe4e1")
       (x11/misty-rose2            "#eed5d2")
       (x11/misty-rose3            "#cdb7b5")
       (x11/misty-rose4            "#8b7d7b")
       (x11/moccasin               "#ffe4b5")
       (x11/navajo-white           "#ffdead")
       (x11/navajo-white1          "#ffdead")
       (x11/navajo-white2          "#eecfa1")
       (x11/navajo-white3          "#cdb38b")
       (x11/navajo-white4          "#8b795e")
       (x11/navy                   "#000080")
       (x11/navy-blue              "#000080")
       (x11/old-lace               "#fdf5e6")
       (x11/olive-drab             "#6b8e23")
       (x11/olive-drab1            "#c0ff3e")
       (x11/olive-drab2            "#b3ee3a")
       (x11/olive-drab3            "#9acd32")
       (x11/olive-drab4            "#698b22")
       (x11/orange                 "#ffa500")
       (x11/orange-red             "#ff4500")
       (x11/orange-red1            "#ff4500")
       (x11/orange-red2            "#ee4000")
       (x11/orange-red3            "#cd3700")
       (x11/orange-red4            "#8b2500")
       (x11/orange1                "#ffa500")
       (x11/orange2                "#ee9a00")
       (x11/orange3                "#cd8500")
       (x11/orange4                "#8b5a00")
       (x11/orchid                 "#da70d6")
       (x11/orchid1                "#ff83fa")
       (x11/orchid2                "#ee7ae9")
       (x11/orchid3                "#cd69c9")
       (x11/orchid4                "#8b4789")
       (x11/pale-goldenrod         "#eee8aa")
       (x11/pale-green             "#98fb98")
       (x11/pale-green1            "#9aff9a")
       (x11/pale-green2            "#90ee90")
       (x11/pale-green3            "#7ccd7c")
       (x11/pale-green4            "#548b54")
       (x11/pale-turquoise         "#afeeee")
       (x11/pale-turquoise1        "#bbffff")
       (x11/pale-turquoise2        "#aeeeee")
       (x11/pale-turquoise3        "#96cdcd")
       (x11/pale-turquoise4        "#668b8b")
       (x11/pale-violet-red        "#db7093")
       (x11/pale-violet-red1       "#ff82ab")
       (x11/pale-violet-red2       "#ee799f")
       (x11/pale-violet-red3       "#cd6889")
       (x11/pale-violet-red4       "#8b475d")
       (x11/papaya-whip            "#ffefd5")
       (x11/peach-puff             "#ffdab9")
       (x11/peach-puff1            "#ffdab9")
       (x11/peach-puff2            "#eecbad")
       (x11/peach-puff3            "#cdaf95")
       (x11/peach-puff4            "#8b7765")
       (x11/peru                   "#cd853f")
       (x11/pink                   "#ffc0cb")
       (x11/pink1                  "#ffb5c5")
       (x11/pink2                  "#eea9b8")
       (x11/pink3                  "#cd919e")
       (x11/pink4                  "#8b636c")
       (x11/plum                   "#dda0dd")
       (x11/plum1                  "#ffbbff")
       (x11/plum2                  "#eeaeee")
       (x11/plum3                  "#cd96cd")
       (x11/plum4                  "#8b668b")
       (x11/powder-blue            "#b0e0e6")
       (x11/purple                 "#a020f0")
       (x11/purple1                "#9b30ff")
       (x11/purple2                "#912cee")
       (x11/purple3                "#7d26cd")
       (x11/purple4                "#551a8b")
       (x11/red                    "#ff0000")
       (x11/red1                   "#ff0000")
       (x11/red2                   "#ee0000")
       (x11/red3                   "#cd0000")
       (x11/red4                   "#8b0000")
       (x11/rosy-brown             "#bc8f8f")
       (x11/rosy-brown1            "#ffc1c1")
       (x11/rosy-brown2            "#eeb4b4")
       (x11/rosy-brown3            "#cd9b9b")
       (x11/rosy-brown4            "#8b6969")
       (x11/royal-blue             "#4169e1")
       (x11/royal-blue1            "#4876ff")
       (x11/royal-blue2            "#436eee")
       (x11/royal-blue3            "#3a5fcd")
       (x11/royal-blue4            "#27408b")
       (x11/saddle-brown           "#8b4513")
       (x11/salmon                 "#fa8072")
       (x11/salmon1                "#ff8c69")
       (x11/salmon2                "#ee8262")
       (x11/salmon3                "#cd7054")
       (x11/salmon4                "#8b4c39")
       (x11/sandy-brown            "#f4a460")
       (x11/sea-green              "#2e8b57")
       (x11/sea-green1             "#54ff9f")
       (x11/sea-green2             "#4eee94")
       (x11/sea-green3             "#43cd80")
       (x11/sea-green4             "#2e8b57")
       (x11/seashell               "#fff5ee")
       (x11/seashell1              "#fff5ee")
       (x11/seashell2              "#eee5de")
       (x11/seashell3              "#cdc5bf")
       (x11/seashell4              "#8b8682")
       (x11/sienna                 "#a0522d")
       (x11/sienna1                "#ff8247")
       (x11/sienna2                "#ee7942")
       (x11/sienna3                "#cd6839")
       (x11/sienna4                "#8b4726")
       (x11/sky-blue               "#87ceeb")
       (x11/sky-blue1              "#87ceff")
       (x11/sky-blue2              "#7ec0ee")
       (x11/sky-blue3              "#6ca6cd")
       (x11/sky-blue4              "#4a708b")
       (x11/slate-blue             "#6a5acd")
       (x11/slate-blue1            "#836fff")
       (x11/slate-blue2            "#7a67ee")
       (x11/slate-blue3            "#6959cd")
       (x11/slate-blue4            "#473c8b")
       (x11/slate-gray             "#708090")
       (x11/slate-gray1            "#c6e2ff")
       (x11/slate-gray2            "#b9d3ee")
       (x11/slate-gray3            "#9fb6cd")
       (x11/slate-gray4            "#6c7b8b")
       (x11/slate-grey             "#708090")
       (x11/snow                   "#fffafa")
       (x11/snow1                  "#fffafa")
       (x11/snow2                  "#eee9e9")
       (x11/snow3                  "#cdc9c9")
       (x11/snow4                  "#8b8989")
       (x11/spring-green           "#00ff7f")
       (x11/spring-green1          "#00ff7f")
       (x11/spring-green2          "#00ee76")
       (x11/spring-green3          "#00cd66")
       (x11/spring-green4          "#008b45")
       (x11/steel-blue             "#4682b4")
       (x11/steel-blue1            "#63b8ff")
       (x11/steel-blue2            "#5cacee")
       (x11/steel-blue3            "#4f94cd")
       (x11/steel-blue4            "#36648b")
       (x11/tan                    "#d2b48c")
       (x11/tan1                   "#ffa54f")
       (x11/tan2                   "#ee9a49")
       (x11/tan3                   "#cd853f")
       (x11/tan4                   "#8b5a2b")
       (x11/thistle                "#d8bfd8")
       (x11/thistle1               "#ffe1ff")
       (x11/thistle2               "#eed2ee")
       (x11/thistle3               "#cdb5cd")
       (x11/thistle4               "#8b7b8b")
       (x11/tomato                 "#ff6347")
       (x11/tomato1                "#ff6347")
       (x11/tomato2                "#ee5c42")
       (x11/tomato3                "#cd4f39")
       (x11/tomato4                "#8b3626")
       (x11/turquoise              "#40e0d0")
       (x11/turquoise1             "#00f5ff")
       (x11/turquoise2             "#00e5ee")
       (x11/turquoise3             "#00c5cd")
       (x11/turquoise4             "#00868b")
       (x11/violet                 "#ee82ee")
       (x11/violet-red             "#d02090")
       (x11/violet-red1            "#ff3e96")
       (x11/violet-red2            "#ee3a8c")
       (x11/violet-red3            "#cd3278")
       (x11/violet-red4            "#8b2252")
       (x11/wheat                  "#f5deb3")
       (x11/wheat1                 "#ffe7ba")
       (x11/wheat2                 "#eed8ae")
       (x11/wheat3                 "#cdba96")
       (x11/wheat4                 "#8b7e66")
       (x11/white                  "#ffffff")
       (x11/white-smoke            "#f5f5f5")
       (x11/yellow                 "#ffff00")
       (x11/yellow-green           "#9acd32")
       (x11/yellow1                "#ffff00")
       (x11/yellow2                "#eeee00")
       (x11/yellow3                "#cdcd00")
       (x11/yellow4                "#8b8b00")

       (mint-y/green "#8fa876")
       (mint-x/black "#2f2f2f")
       (mint-x/white "#cccccc")

       ;; theme colors

       (fontaine/fg-black      x11/black)
       (fontaine/fg-brown      x11/brown4)
       (fontaine/fg-red        x11/red2)
       (fontaine/fg-orange     solar/fg-orange)
       (fontaine/fg-yellow     nil)
       (fontaine/fg-green      dutch/turkish-aqua)

       (fontaine/black         x11/black)
       (fontaine/black-ui      mint-x/black)

       (fontaine/blue          dutch/merchant-marine-blue)
       (fontaine/blue-1        french/azraq-blue)
       (fontaine/blue-bright   turkish/neon-blue)
       (fontaine/blue-dark     dutch/20000-leagues-under-the-sea)
       (fontaine/blue-deep     "#00bfff")
       (fontaine/blue-light    swedish/free-speech-blue)
       (fontaine/blue-purple   aussie/blurple)

       (fontaine/brown         "#8b4513")

       (fontaine/cyan-dark     material/fg-cyan-900)

       (fontaine/gray          flat/asbestos)
       (fontaine/gray-medium   russian/pencil-lead)
       (fontaine/gray-light    "#a6a6a6")
       (fontaine/gray-ui-1     ibm/cool-gray-70)
       (fontaine/gray-ui-2     ibm/cool-gray-60)
       (fontaine/gray-ui-3     ibm/cool-gray-50)

       (fontaine/green         mint-y/green)
       (fontaine/green-1       aussie/pure-apple)
       (fontaine/green-dark    ibm/green-60)
       (fontaine/green-ui-1    material/bg-light-green-600)
       (fontaine/green-ui-2    material/bg-light-green-600)
       (fontaine/green-ui-3    material/bg-light-green-400)

       (fontaine/green-blue    aussie/greenland-green)

       (fontaine/orange        material/fg-orange-900)
       (fontaine/orange-1      aussie/quince-jelly)
       (fontaine/orange-2      ibm/orange-50)
       (fontaine/orange-dark   solar/fg-orange)
       (fontaine/orange-yellow german/nyc-taxi)

       (fontaine/pink          indian/saquatch-socks)
       (fontaine/pink-1        aussie/carmine-pink)

       (fontaine/purple        canadian/nasu-purple)
       (fontaine/purple-red    indian/magenta-purple)

       (fontaine/red           solar/fg-red)
       (fontaine/red-1         french/mandarin-red)
       (fontaine/red-bright    "red")
       (fontaine/red-dark      "firebrick")

       (fontaine/turquoise     swedish/fresh-turquoise)

       (fontaine/violet-red    "#d02090")

       (fontaine/white         "white")
       (fontaine/white-ui      mint-x/white)

       (fontaine/yellow        turkish/dorn-yellow)

       ;; theme elements

       (fontaine/array                  fontaine/purple)
       (fontaine/box                    fontaine/white)
       (fontaine/builtin                fontaine/cyan-dark)
       (fontaine/comment                fontaine/red-dark)
       (fontaine/constant               fontaine/green-dark)
       (fontaine/current-line           fontaine/white)
       (fontaine/cursor                 fontaine/black)
       (fontaine/declare                fontaine/gray)
       (fontaine/error                  fontaine/red-bright)
       (fontaine/function               fontaine/blue-light)
       (fontaine/hash                   fontaine/pink-1)
       (fontaine/keyword                fontaine/black)
       (fontaine/line-number            fontaine/gray-medium)
       (fontaine/match                  fontaine/blue-bright)
       (fontaine/mode-line-active-bg    fontaine/black-ui)
       (fontaine/mode-line-active-fg    fontaine/white-ui)
       (fontaine/mode-line-inactive-bg  fontaine/black-ui)
       (fontaine/mode-line-inactive-fg  fontaine/white-ui)
       (fontaine/non-over               fontaine/gray-medium)
       (fontaine/operator               fontaine/orange-dark)
       (fontaine/paren-match            fontaine/turquoise)
       (fontaine/paren-mismatch-bg      fontaine/yellow)
       (fontaine/paren-mismatch-fg      fontaine/red-bright)
       (fontaine/paren-no-match-bg      fontaine/red-bright)
       (fontaine/paren-no-match-fg      fontaine/yellow)
       (fontaine/powerline-active1-bg   fontaine/mode-line-active-bg)
       (fontaine/powerline-active1-fg   fontaine/mode-line-active-fg)
       (fontaine/powerline-active2-bg   fontaine/green-ui-2)
       (fontaine/powerline-active2-fg   fontaine/black)
       (fontaine/powerline-active3-bg   fontaine/green-ui-3)
       (fontaine/powerline-active3-fg   fontaine/black)
       (fontaine/powerline-inactive1-bg fontaine/mode-line-inactive-bg)
       (fontaine/powerline-inactive1-fg fontaine/mode-line-inactive-fg)
       (fontaine/powerline-inactive2-bg fontaine/gray-ui-2)
       (fontaine/powerline-inactive2-fg fontaine/white-ui)
       (fontaine/powerline-inactive3-bg fontaine/gray-ui-3)
       (fontaine/powerline-inactive3-fg fontaine/white-ui)
       (fontaine/prompt                 fontaine/red)
       (fontaine/rainbow-1              fontaine/purple-red)
       (fontaine/rainbow-2              fontaine/violet-red)
       (fontaine/rainbow-3              fontaine/blue-purple)
       (fontaine/rainbow-4              fontaine/blue-1)
       (fontaine/rainbow-5              fontaine/green-blue)
       (fontaine/rainbow-6              fontaine/green-1)
       (fontaine/rainbow-7              fontaine/orange-1)
       (fontaine/rainbow-8              fontaine/orange-2)
       (fontaine/rainbow-9              fontaine/red-1)
       (fontaine/region                 fontaine/yellow)
       (fontaine/secondary              fontaine/orange-yellow)
       (fontaine/separator              fontaine/gray-light)
       (fontaine/string                 fontaine/brown)
       (fontaine/success                fontaine/green-dark)
       (fontaine/tabbar-default-bg      fontaine/black-ui)
       (fontaine/tabbar-default-fg      fontaine/white-ui)
       ;; (fontaine/tabbar-modified-bg     fontaine/red-bright)
       ;; (fontaine/tabbar-modified-fg     fontaine/white)
       (fontaine/tabbar-selected-bg     "nil")
       (fontaine/tabbar-selected-fg     fontaine/black)
       (fontaine/tabbar-unselected-bg   ibm/cool-gray-70)
       (fontaine/tabbar-unselected-fg   fontaine/white-ui)
       (fontaine/tabbar-modified-s-fg   fontaine/red-bright)
       (fontaine/tabbar-modified-bg     fontaine/red-dark)
       (fontaine/tabbar-modified-fg     fontaine/white-ui)
       (fontaine/type                   fontaine/blue-dark)
       (fontaine/variable               fontaine/blue)
       (fontaine/volatile-highlight     fontaine/blue-deep)
       (fontaine/warning                fontaine/orange)
       )

;; 6 matches for "set-face-attribute" in buffer: *scratch*
;;      48:(set-face-attribute 'tabbar-default nil           fontaine/tabbar-default-bg    fontaine/tabbar-default-fg
;;      55:(set-face-attribute 'tabbar-unselected nil        fontaine/tabbar-unselected-bg fontaine/tabbar-unselected-fg
;;      60:(set-face-attribute 'tabbar-modified nil          fontaine/tabbar-modified-bg   fontaine/tabbar-modified-fg
;;      66:(set-face-attribute 'tabbar-selected nil                                        fontaine/tabbar-selected-fg
;;      72:(set-face-attribute 'tabbar-selected-modified nil                               fontaine/tabbar-modified-s-fg
;;      78:(set-face-attribute 'tabbar-button nil
  ;; (defface tabbar-unselected `((t (:inherit fontaine/variable-pitch :background ,fontaine/tabbar-unselected-bg :foreground ,fontaine/tabbar-unselected-fg))) "Temp face." :group 'font-lock-faces)

  ;; (defface tabbar-selected   `((t (:inherit fontaine/variable-pitch :background ,fontaine/tabbar-selected-bg   :foreground ,fontaine/tabbar-selected-fg :weight bold))) "Temp face." :group 'font-lock-faces)

  ;; (defface tabbar-selected-modified   `((t (:inherit tabbar-selected   :foreground ,fontaine/tabbar-modified-s-fg)))   "Temp face." :group 'font-lock-faces)
  ;; (defface tabbar-unselected-modified `((t (:inherit tabbar-unselected :foreground ,fontaine/tabbar-modified-u-fg :background ,fontaine/tabbar-modified-u-bg))) "Temp face." :group 'font-lock-faces)

  (defface fontaine/mode-line-base '((t (:family "DejaVu Sans" :box (:line-width 1 :color "gray50")))) "Temp face." :group 'font-lock-faces)
  (defface fontaine/variable-pitch '((t (:inherit variable-pitch :height 0.8))) "Temp face." :group 'font-lock-faces)

  (defface tabbar-default           `((t (:background ,fontaine/tabbar-default-bg :foreground ,fontaine/tabbar-default-fg))) "Temp face." :group 'font-lock-faces)
  (defface tabbar-unselected        `((t (:inherit fontaine/variable-pitch :foreground ,fontaine/tabbar-unselected-fg :background ,fontaine/tabbar-unselected-bg))) "Temp face." :group 'font-lock-faces)
  (defface tabbar-modified          `((t (:inherit tabbar-unselected       :foreground ,fontaine/tabbar-modified-fg   :background ,fontaine/tabbar-modified-bg))) "Temp face." :group 'font-lock-faces)
  (defface tabbar-selected          `((t (:inherit fontaine/variable-pitch :foreground ,fontaine/tabbar-selected-fg :background "nil" :weight bold))) "Temp face." :group 'font-lock-faces)
  (defface tabbar-selected-modified `((t (:inherit tabbar-selected         :foreground ,fontaine/tabbar-modified-s-fg))) "Temp face." :group 'font-lock-faces)
  (defface tabbar-button            `((t (:inherit tabbar-unselected))) "Temp face." :group 'font-lock-faces)

  (custom-theme-set-faces
   `fontaine
   `(default             ((t (:family ,font-family :height 120 :width normal))))
   ;;
   `(cursor              ((t (:background ,fontaine/cursor))))
   `(region              ((t (:background ,fontaine/region))))
   `(secondary-selection ((t (:background ,fontaine/secondary))))
   ;;
   `(fringe              ((t (:background nil))))
   ;;
   `(error   ((t (:foreground ,fontaine/error   :weight bold))))
   `(success ((t (:foreground ,fontaine/success :weight bold))))
   `(warning ((t (:foreground ,fontaine/warning :weight bold))))
   ;;
   `(mode-line           ((t (:inherit fontaine/mode-line-base :background ,fontaine/mode-line-active-bg   :foreground ,fontaine/mode-line-active-fg))))
   `(mode-line-inactive  ((t (:inherit fontaine/mode-line-base :background ,fontaine/mode-line-inactive-bg :foreground ,fontaine/mode-line-inactive-fg))))

   `(powerline-active1   ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-active1-bg :foreground ,fontaine/powerline-active1-fg :weight bold))))
   `(powerline-active2   ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-active2-bg :foreground ,fontaine/powerline-active2-fg))))
   `(powerline-active3   ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-active3-bg :foreground ,fontaine/powerline-active3-fg))))

   `(powerline-inactive1 ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-inactive1-bg :foreground ,fontaine/powerline-inactive1-fg :weight bold))))
   `(powerline-inactive2 ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-inactive2-bg :foreground ,fontaine/powerline-inactive2-fg))))
   `(powerline-inactive3 ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-inactive3-bg :foreground ,fontaine/powerline-inactive3-fg))))


   `(anzu-mode-line      ((t (:inherit minibuffer-prompt :foreground ,fontaine/match :weight bold))))
   
   ;; `(clips-constant-face             ((t (:foreground ,solar/fg-blue))))
   ;; `(clips-control-face              ((t (:foreground "cyan4"         :weight bold))))
   ;; `(clips-declaration-face          ((t (:foreground "gray40"        :weight bold))))
   ;; `(clips-function-face             ((t (:foreground ,solar/fg-green :weight bold))))
   ;; `(clips-global-variable-face      ((t (:foreground "navy"))))
   ;; `(clips-logical-face              ((t (:foreground ,solar/fg-cyan  :weight bold))))
   ;; `(clips-object-match-face         ((t (:foreground "purple"        :weight bold))))
   ;; `(clips-variable-face             ((t (:foreground "royalblue"))))
   ;; `(clips-verb-face                 ((t (:foreground "green4"        :weight bold))))

   ;; `(clips-log-activate-face         ((t (:foreground ,solar/fg-magenta :weight bold))))
   ;; `(clips-log-deactivate-face       ((t (:foreground ,solar/fg-magenta))))
   ;; `(clips-log-make-instance-face    ((t (:foreground ,solar/fg-blue :weight bold))))
   ;; `(clips-log-unmake-instance-face  ((t (:foreground ,solar/fg-blue))))
   ;; `(clips-log-fire-face             ((t (:foreground "blue3" :weight bold))))
   ;; `(clips-log-assert-fact-face      ((t (:foreground ,solar/fg-cyan :weight bold))))
   ;; `(clips-log-retract-fact-face     ((t (:foreground ,solar/fg-cyan))))
   ;; `(clips-log-error-face            ((t (:foreground ,fontaine/error1 :weight bold))))
   ;; `(clips-log-fatal-face            ((t (:foreground ,fontaine/error1 :background ,fontaine/ :weight bold))))
   ;; `(clips-log-pass-face             ((t (:foreground "ForestGreen" :weight bold))))

   `(comint-highlight-prompt         ((t (:foreground ,fontaine/prompt :weight bold))))

   `(compilation-column-number       ((t (:weight bold))))
   `(compilation-line-number         ((t (:weight bold))))
   `(compilation-warning             ((t (:foreground ,fontaine/warning :weight bold))))

   `(cperl-array-face                ((t (:foreground ,fontaine/array    :weight bold))))
   `(cperl-hash-face                 ((t (:foreground ,fontaine/hash     :weight bold))))
   `(cperl-nonoverridable-face       ((t (:foreground ,fontaine/non-over :weight bold))))

   `(font-lock-comment-face          ((t (:foreground ,fontaine/comment :slant italic))))
   `(font-lock-doc-face              ((t (:foreground ,fontaine/comment :slant italic :weight bold))))

   `(font-lock-string-face           ((t (:foreground ,fontaine/string :slant italic))))
   ;; `(font-lock-doc-string-face       ((t (:foreground ,fontaine/string :slant italic))))

   `(font-lock-builtin-face          ((t (:foreground ,fontaine/builtin    :weight bold))))
   `(font-lock-constant-face         ((t (:foreground ,fontaine/constant   :weight bold))))
   `(font-lock-function-name-face    ((t (:foreground ,fontaine/function   :weight bold))))
   `(font-lock-keyword-face          ((t (:foreground ,fontaine/keyword    :weight bold))))
   `(font-lock-type-face             ((t (:foreground ,fontaine/type       :weight bold))))
   `(font-lock-variable-name-face    ((t (:foreground ,fontaine/variable   :weight bold))))
   `(font-lock-warning-face          ((t (:foreground ,fontaine/warning    :weight bold))))

   `(git-gutter:added                ((t (:foreground ,solar/fg-green      :weight bold))))
   `(git-gutter:deleted              ((t (:foreground ,fontaine/red        :weight bold))))
   `(git-gutter:modified             ((t (:foreground ,fontaine/blue       :weight bold))))

   ;; `(hes-escape-backslash-face ((t (:weight bold))))
   ;; `(hes-escape-face           ((t (:weight bold))))
   ;; `(hes-escape-sequence-face  ((t (:weight bold))))

   `(highlight ((t (:background ,fontaine/match))))

   ;; `(highlight-operators-face ((t (:foreground ,fontaine/operator :weight bold))))

   `(hl-line ((t (:background ,fontaine/current-line))))

   `(isearch ((t (:background ,fontaine/match))))

   `(line-number              ((t (:foreground ,fontaine/line-number))))
   `(line-number-current-line ((t (:foreground ,fontaine/line-number :weight bold))))

   `(match ((t (:background ,fontaine/match))))

   `(paren-face-match    ((t (:background ,fontaine/paren-match))))
   `(paren-face-mismatch ((t (:background ,fontaine/paren-mismatch-bg :foreground ,fontaine/paren-mismatch-fg))))
   `(paren-face-no-match ((t (:background ,fontaine/paren-no-match-bg :foreground ,fontaine/paren-no-match-fg))))

   `(rainbow-delimiters-base-face    ((t (:inherit unspecified :weight bold))))
   `(rainbow-delimiters-depth-1-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-1))))
   `(rainbow-delimiters-depth-2-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-2))))
   `(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-3))))
   `(rainbow-delimiters-depth-4-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-4))))
   `(rainbow-delimiters-depth-5-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-5))))
   `(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-6))))
   `(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-7))))
   `(rainbow-delimiters-depth-8-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-8))))
   `(rainbow-delimiters-depth-9-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-9))))
   ;; `(sh-heredoc                      ((t (:foreground ,fontaine/string))))
   ;; `(sh-heredoc-face                 ((t (:foreground ,fontaine/comment))))
   ;; `(sh-quoted-exec                  ((t (:foreground "magenta3" :slant italic)))) ;; !!!

   `(vhl/default-face ((t (:background ,fontaine/volatile-highlight))))

   ;; `(web-mode-json-context-face      ((t (:foreground ,material/fg-pink-500 :weight bold)))) ;; !!!
   `(web-mode-json-key-face          ((t (:weight bold))))
   ))
 ;;
(message "Loading fontaine-theme...done")
(provide-theme 'fontaine)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; fontaine-theme.el ends here
;; rainbow ((((((((()))))))))
