;;; fontaine-theme.el --- Dark on light theme -*-Emacs-Lisp-*-

;;         Copyright © 2016-2019  Tom Fontaine

;; Author: Tom Fontaine
;; Date:   19-Aug-2016

;; Permission is hereby granted, free of charge, to any person obtaining a
;; copy of this software and associated documentation files (the "Software",
;; to deal in the Software without restriction, including without limitation
;; the rights to use, copy, modify, merge, publish, distribute, sublicense,
;; and/or sell copies of the Software, and to permit persons to whom the
;; Software is furnished to do so, subject to the following conditions:

;; The above copyright notice and this permission notice shall be included in
;; all copies or substantial portions of the Software.

;; Except as contained in this notice, the name(s of the above copyright
;; holders shall not be used in advertising or otherwise to promote the sale,
;; use or other dealings in this Software without prior written authorization.

;; The software is provided "As Is", without warranty of any kind, express or
;; implied, including but not limited to the warranties of merchantability,
;; fitness for a particular purpose and noninfringement. In no event shall
;; the authors or copyright holders be liable for any claim, damages or other
;; liability, whether in an action of contract, tort or otherwise, arising
;; from, out of or in connection with the software or the use or other
;; dealings in the software.

;;; Commentary:

;; Revision:    16-Nov-2016 Added vhl/default-face
;;              04-Jan-2017 Added material colors
;;              05-Jan-2017 Converting from blue to Mint
;;              25-Apr-2017 Added flat  colors
;;              19-Jun-2018 Added multiple palettes
;;              02-Apr-2019 Changed font-family selection method
;;                          Added ‘Hack’ and made it the default font
;;                          Added ‘Source Code Pro’
;;              04-Apr-2019 Added ‘Cousine’
;;                          Added ‘CamingoCode’
;;                          Added ‘Fantasque’
;;              09-Jun-2019 Added ‘Nord’ colors
;;                          Added ‘Srcsery’ colors
;;              09-Jul-2019 Added ‘Victor’ font
;;              21-Jan-2020 Added ‘JetBrains’ font
;;              28-Jan-2020 Added ‘Iosevka’ and ‘IosevkaSlab’ font
;;              23-Sep-2020 Added ‘canva’ colors
;;                          Cleaned up mintdefinitions
;;

;;; Code:

(message "Loading fontaine-theme...")

(deftheme fontaine)

(load-file "./colors/american.el")
(load-file "./colors/aussie.el")
(load-file "./colors/british.el")
(load-file "./colors/canadian.el")
(load-file "./colors/canva.el")
(load-file "./colors/chinese.el")
(load-file "./colors/color-blind.el")
(load-file "./colors/dutch.el")
(load-file "./colors/flat.el")
(load-file "./colors/french.el")
(load-file "./colors/x11.el")

;; (add-to-list 'default-frame-alist '(alpha . (92 . 90)))

;; Windows fonts
;;   Consolas
;;   Office Code Pro
;;   Office Code Pro D
;;   Source Code Pro
;;   Cousine
;;   Fantasque
;;   Courier New

;;   Iosevka,Iosevka Light Extended:style=Light Extended,Regular

(let* ((font-family-list (font-family-list))

       (camingo         (car (member "CamingoCode"      font-family-list)))
       (consolas        (car (member "Consolas"         font-family-list)))
       (courier         (car (member "Courier 10 Pitch" font-family-list)))
       (cousine         (car (member "Cousine"          font-family-list)))
       (deja-vu         (car (member "DejaVu Sans Mono" font-family-list)))
       (fantasque       (car (member "Fantasque"        font-family-list)))
       (iosevka         (car (member "Iosevka"          font-family-list)))
       (iosevka-slab    (car (member "Iosevka Slab"     font-family-list)))
       (victor          (car (member "Victor"           font-family-list)))
       (hack            (car (member "Hack"             font-family-list)))
       (jet             (car (member "Jet"              font-family-list)))
       (source-code-pro (car (member "Source Code Pro"  font-family-list)))

       (font-family (or hack deja-vu consolas source-code-pro jet iosevka iosevka-slab cousine camingo fantasque victor courier))

       ;; named color definitions











       (german/algal-fuel      "#20bf6b")
       (german/beniukon-bronze "#fa8231")
       (german/blue-grey       "#778ca3")
       (german/blue-horizon    "#4b6584")
       (german/boyzone         "#2d98da")
       (german/c64-ntsc        "#4b7bec")
       (german/desire          "#eb3b5a")
       (german/flirtatious     "#fed330")
       (german/fusion-red      "#fc5c65")
       (german/gloomy-purple   "#8854d0")
       (german/high-blue       "#45aaf2")
       (german/innuendo        "#a5b1c2")
       (german/lighter-purple  "#a55eea")
       (german/maximum-blue    "#2bcbba")
       (german/nyc-taxi        "#f7b731")
       (german/orange-hibiscus "#fd9644")
       (german/reptile-green   "#26de81")
       (german/royal-blue      "#3867d6")
       (german/turquoise-topaz "#0fb9b1")
       (german/twinkle-blue    "#d1d8e0")

       (ibm/aqua-01 "#d1f0f7")
       (ibm/aqua-10 "#a0e3f0")
       (ibm/aqua-20 "#71cddd")
       (ibm/aqua-30 "#00b6cb")
       (ibm/aqua-40 "#12a3b4")
       (ibm/aqua-50 "#188291")
       (ibm/aqua-60 "#17616b")
       (ibm/aqua-70 "#164d56")
       (ibm/aqua-80 "#13393e")
       (ibm/aqua-90 "#122a2e")

       (ibm/blue-01 "#e1ebf7")
       (ibm/blue-10 "#c8daf4")
       (ibm/blue-20 "#a8c0f3")
       (ibm/blue-30 "#79a6f6")
       (ibm/blue-40 "#5392ff")
       (ibm/blue-50 "#2d74da")
       (ibm/blue-60 "#1f57a4")
       (ibm/blue-70 "#25467a")
       (ibm/blue-80 "#1d3458")
       (ibm/blue-90 "#19273c")

       (ibm/cerulean-01 "#deedf7")
       (ibm/cerulean-10 "#c2dbf4")
       (ibm/cerulean-20 "#95c4f3")
       (ibm/cerulean-30 "#56acf2")
       (ibm/cerulean-40 "#009bef")
       (ibm/cerulean-50 "#047cc0")
       (ibm/cerulean-60 "#175d8d")
       (ibm/cerulean-70 "#1c496d")
       (ibm/cerulean-80 "#1d364d")
       (ibm/cerulean-90 "#1b2834")

       (ibm/cool-gray-01 "#e3ecec")
       (ibm/cool-gray-10 "#d0dada")
       (ibm/cool-gray-20 "#b8c1c1")
       (ibm/cool-gray-30 "#9fa7a7")
       (ibm/cool-gray-40 "#8c9696")
       (ibm/cool-gray-50 "#6f7878")
       (ibm/cool-gray-60 "#535a5a")
       (ibm/cool-gray-70 "#424747")
       (ibm/cool-gray-80 "#343334")
       (ibm/cool-gray-90 "#272727")

       (ibm/cool-white-1 "#fbfcfc")
       (ibm/cool-white-2 "#f8fafa")
       (ibm/cool-white-3 "#f4f7f7")
       (ibm/cool-white-4 "#f0f4f4")

       (ibm/gold-01 "#f5e8db")
       (ibm/gold-10 "#ffd191")
       (ibm/gold-20 "#ffb000")
       (ibm/gold-30 "#e39d14")
       (ibm/gold-40 "#c4881c")
       (ibm/gold-50 "#9c6d1e")
       (ibm/gold-60 "#74521b")
       (ibm/gold-70 "#5b421c")
       (ibm/gold-80 "#42301b")
       (ibm/gold-90 "#2f261c")

       (ibm/gray-01 "#eaeaea")
       (ibm/gray-10 "#d8d8d8")
       (ibm/gray-20 "#c0bfc0")
       (ibm/gray-30 "#a6a5a6")
       (ibm/gray-40 "#949394")
       (ibm/gray-50 "#777677")
       (ibm/gray-60 "#595859")
       (ibm/gray-70 "#464646")
       (ibm/gray-80 "#343334")
       (ibm/gray-90 "#272727")

       (ibm/green-01 "#cef3d1")
       (ibm/green-10 "#89eda0")
       (ibm/green-20 "#57d785")
       (ibm/green-30 "#34bc6e")
       (ibm/green-40 "#00aa5e")
       (ibm/green-50 "#00884b")
       (ibm/green-60 "#116639")
       (ibm/green-70 "#12512e")
       (ibm/green-80 "#123b22")
       (ibm/green-90 "#112c1b")

       (ibm/indigo-01 "#e9e8ff")
       (ibm/indigo-10 "#dcd4f7")
       (ibm/indigo-20 "#c7b6f7")
       (ibm/indigo-30 "#ae97f4")
       (ibm/indigo-40 "#9b82f3")
       (ibm/indigo-50 "#785ef0")
       (ibm/indigo-60 "#5a3ec8")
       (ibm/indigo-70 "#473793")
       (ibm/indigo-80 "#352969")
       (ibm/indigo-90 "#272149")

       (ibm/lime-01 "#d7f4bd")
       (ibm/lime-10 "#b4e876")
       (ibm/lime-20 "#95d13c")
       (ibm/lime-30 "#81b532")
       (ibm/lime-40 "#73a22c")
       (ibm/lime-50 "#5b8121")
       (ibm/lime-60 "#426200")
       (ibm/lime-70 "#374c1a")
       (ibm/lime-80 "#283912")
       (ibm/lime-90 "#1f2a10")

       (ibm/magenta-01 "#f5e7eb")
       (ibm/magenta-10 "#f5cedb")
       (ibm/magenta-20 "#f7aac3")
       (ibm/magenta-30 "#f87eac")
       (ibm/magenta-40 "#ff509e")
       (ibm/magenta-50 "#dc267f")
       (ibm/magenta-60 "#a91560")
       (ibm/magenta-70 "#831b4c")
       (ibm/magenta-80 "#5d1a38")
       (ibm/magenta-90 "#401a29")

       (ibm/neutral-white-1 "#fcfcfc")
       (ibm/neutral-white-2 "#f9f9f9")
       (ibm/neutral-white-3 "#f6f6f6")
       (ibm/neutral-white-4 "#f3f3f3")

       (ibm/orange-01 "#f5e8de")
       (ibm/orange-10 "#fdcfad")
       (ibm/orange-20 "#fcaf6d")
       (ibm/orange-30 "#fe8500")
       (ibm/orange-40 "#db7c00")
       (ibm/orange-50 "#ad6418")
       (ibm/orange-60 "#814b19")
       (ibm/orange-70 "#653d1b")
       (ibm/orange-80 "#482e1a")
       (ibm/orange-90 "#33241c")

       (ibm/peach-01 "#f7e7e2")
       (ibm/peach-10 "#f8d0c3")
       (ibm/peach-20 "#faad96")
       (ibm/peach-30 "#fc835c")
       (ibm/peach-40 "#fe6100")
       (ibm/peach-50 "#c45433")
       (ibm/peach-60 "#993a1d")
       (ibm/peach-70 "#782f1c")
       (ibm/peach-80 "#56251a")
       (ibm/peach-90 "#3a201b")

       (ibm/purple-01 "#f7e4fb")
       (ibm/purple-10 "#efcef3")
       (ibm/purple-20 "#e4adea")
       (ibm/purple-30 "#d68adf")
       (ibm/purple-40 "#cb71d7")
       (ibm/purple-50 "#c22dd5")
       (ibm/purple-60 "#9320a2")
       (ibm/purple-70 "#71237c")
       (ibm/purple-80 "#501e58")
       (ibm/purple-90 "#3b1a40")

       (ibm/red-01 "#f7e6e6")
       (ibm/red-10 "#fccec7")
       (ibm/red-20 "#ffaa9d")
       (ibm/red-30 "#ff806c")
       (ibm/red-40 "#ff5c49")
       (ibm/red-50 "#e62325")
       (ibm/red-60 "#aa231f")
       (ibm/red-70 "#83231e")
       (ibm/red-80 "#5c1f1b")
       (ibm/red-90 "#3e1d1b")

       (ibm/teal-01 "#c0f5e8")
       (ibm/teal-10 "#8ee9d4")
       (ibm/teal-20 "#40d5bb")
       (ibm/teal-30 "#00baa1")
       (ibm/teal-40 "#00a78f")
       (ibm/teal-50 "#008673")
       (ibm/teal-60 "#006456")
       (ibm/teal-70 "#124f44")
       (ibm/teal-80 "#133a32")
       (ibm/teal-90 "#122b26")

       (ibm/ultramarine-01 "#e7e9f7")
       (ibm/ultramarine-10 "#d1d7f4")
       (ibm/ultramarine-20 "#b0bef3")
       (ibm/ultramarine-30 "#89a2f6")
       (ibm/ultramarine-40 "#648fff")
       (ibm/ultramarine-50 "#3c6df0")
       (ibm/ultramarine-60 "#3151b7")
       (ibm/ultramarine-70 "#2e3f8f")
       (ibm/ultramarine-80 "#252e6a")
       (ibm/ultramarine-90 "#20214f")

       (ibm/violet-01 "#ece8f5")
       (ibm/violet-10 "#e2d2f4")
       (ibm/violet-20 "#d2b5f0")
       (ibm/violet-30 "#bf93eb")
       (ibm/violet-40 "#b07ce8")
       (ibm/violet-50 "#9753e1")
       (ibm/violet-60 "#7732bb")
       (ibm/violet-70 "#602797")
       (ibm/violet-80 "#44216a")
       (ibm/violet-90 "#321c4c")

       (ibm/warm-gray-01 "#efe9e9")
       (ibm/warm-gray-10 "#e2d5d5")
       (ibm/warm-gray-20 "#ccbcbc")
       (ibm/warm-gray-30 "#b4a1a1")
       (ibm/warm-gray-40 "#9e9191")
       (ibm/warm-gray-50 "#7d7373")
       (ibm/warm-gray-60 "#5f5757")
       (ibm/warm-gray-70 "#4b4545")
       (ibm/warm-gray-80 "#373232")
       (ibm/warm-gray-90 "#2a2626")

       (ibm/warm-white-1 "#fdfcfc")
       (ibm/warm-white-2 "#fbf8f8")
       (ibm/warm-white-3 "#f9f6f6")
       (ibm/warm-white-4 "#f6f3f3")

       (ibm/yellow-01 "#fbeaae")
       (ibm/yellow-10 "#fed500")
       (ibm/yellow-20 "#e3bc13")
       (ibm/yellow-30 "#c6a21a")
       (ibm/yellow-40 "#b3901f")
       (ibm/yellow-50 "#91721f")
       (ibm/yellow-60 "#70541b")
       (ibm/yellow-70 "#5b421a")
       (ibm/yellow-80 "#452f18")
       (ibm/yellow-90 "#372118")

       (indian/bluebell             "#3b3b98")
       (indian/bright-ube           "#d6a2e8")
       (indian/clear-chill          "#1b9cfc")
       (indian/ending-navy-blue     "#182c61")
       (indian/falling-star         "#cad3c8")
       (indian/fiery-fuchsia        "#b33771")
       (indian/georgia-peach        "#fd7272")
       (indian/highlighter-lavender "#82589f")
       (indian/honey-glow           "#eab543")
       (indian/keppel               "#58b19f")
       (indian/magenta-purple       "#6d214f")
       (indian/oasis-stream         "#9aecdb")
       (indian/orchid-orange        "#fea47f")
       (indian/pine-glade           "#bdc581")
       (indian/rich-gardenia        "#f97f51")
       (indian/saquatch-socks       "#fc427b")
       (indian/sarawak-white-pepper "#f8efba")
       (indian/ships-officer        "#2c3a47")
       (indian/spiro-disco-ball     "#25ccf7")
       (indian/sweet-garden         "#55e6c1")

       (material/amber-050  "#fff8e1")
       (material/amber-100  "#ffecb3")
       (material/amber-200  "#ffe082")
       (material/amber-300  "#ffd54f")
       (material/amber-400  "#ffca28")
       (material/amber-500  "#ffc107")
       (material/amber-600  "#ffb300")
       (material/amber-700  "#ffa000")
       (material/amber-800  "#ff8f00")
       (material/amber-900  "#ff6f00")
       (material/amber-A100 "#ffe57f")
       (material/amber-A200 "#ffd740")
       (material/amber-A400 "#ffc400")
       (material/amber-A700 "#ffab00")

       (material/blue-050  "#e3f2fd")
       (material/blue-100  "#bbdefb")
       (material/blue-200  "#90caf9")
       (material/blue-300  "#64b5f6")
       (material/blue-400  "#42a5f5")
       (material/blue-500  "#2196f3")
       (material/blue-600  "#1e88e5")
       (material/blue-700  "#1976d2")
       (material/blue-800  "#1565c0")
       (material/blue-900  "#0d47a1")
       (material/blue-A100 "#82b1ff")
       (material/blue-A200 "#448aff")
       (material/blue-A400 "#2979ff")
       (material/blue-A700 "#2962ff")

       (material/blue-grey-050 "#eceff1")
       (material/blue-grey-100 "#cfd8dc")
       (material/blue-grey-200 "#b0bec5")
       (material/blue-grey-300 "#90a4ae")
       (material/blue-grey-400 "#78909c")
       (material/blue-grey-500 "#607d8b")
       (material/blue-grey-600 "#546e7a")
       (material/blue-grey-700 "#455a64")
       (material/blue-grey-800 "#37474f")
       (material/blue-grey-900 "#263238")

       (material/brown-050 "#efebe9")
       (material/brown-100 "#d7ccc8")
       (material/brown-200 "#bcaaa4")
       (material/brown-300 "#a1887f")
       (material/brown-400 "#8d6e63")
       (material/brown-500 "#795548")
       (material/brown-600 "#6d4c41")
       (material/brown-700 "#5d4037")
       (material/brown-800 "#4e342e")
       (material/brown-900 "#3e2723")

       (material/cyan-050  "#e0f7fa")
       (material/cyan-100  "#b2ebf2")
       (material/cyan-200  "#80deea")
       (material/cyan-300  "#4dd0e1")
       (material/cyan-400  "#26c6da")
       (material/cyan-500  "#00bcd4")
       (material/cyan-600  "#00acc1")
       (material/cyan-700  "#0097a7")
       (material/cyan-800  "#00838f")
       (material/cyan-900  "#006064")
       (material/cyan-A100 "#84ffff")
       (material/cyan-A200 "#18ffff")
       (material/cyan-A400 "#00e5ff")
       (material/cyan-A700 "#00b8d4")

       (material/deep-orange-050  "#fbe9e7")
       (material/deep-orange-100  "#ffccbc")
       (material/deep-orange-200  "#ffab91")
       (material/deep-orange-300  "#ff8a65")
       (material/deep-orange-400  "#ff7043")
       (material/deep-orange-500  "#ff5722")
       (material/deep-orange-600  "#f4511e")
       (material/deep-orange-700  "#e64a19")
       (material/deep-orange-800  "#d84315")
       (material/deep-orange-900  "#bf360c")
       (material/deep-orange-A100 "#ff9e80")
       (material/deep-orange-A200 "#ff6e40")
       (material/deep-orange-A400 "#ff3d00")
       (material/deep-orange-A700 "#dd2c00")

       (material/deep-purple-050  "#ede7f6")
       (material/deep-purple-100  "#d1c4e9")
       (material/deep-purple-200  "#b39ddb")
       (material/deep-purple-300  "#9575cd")
       (material/deep-purple-400  "#7e57c2")
       (material/deep-purple-500  "#673ab7")
       (material/deep-purple-600  "#5e35b1")
       (material/deep-purple-700  "#512da8")
       (material/deep-purple-800  "#4527a0")
       (material/deep-purple-900  "#311b92")
       (material/deep-purple-A100 "#b388ff")
       (material/deep-purple-A200 "#7c4dff")
       (material/deep-purple-A400 "#651fff")
       (material/deep-purple-A700 "#6200ea")

       (material/green-050  "#e8f5e9")
       (material/green-100  "#c8e6c9")
       (material/green-200  "#a5d6a7")
       (material/green-300  "#81c784")
       (material/green-400  "#66bb6a")
       (material/green-500  "#4caf50")
       (material/green-600  "#43a047")
       (material/green-700  "#388e3c")
       (material/green-800  "#2e7d32")
       (material/green-900  "#1b5e20")
       (material/green-A100 "#b9f6ca")
       (material/green-A200 "#69f0ae")
       (material/green-A400 "#00e676")
       (material/green-A700 "#00c853")

       (material/grey-050 "#fafafa")
       (material/grey-100 "#f5f5f5")
       (material/grey-200 "#eeeeee")
       (material/grey-300 "#e0e0e0")
       (material/grey-400 "#bdbdbd")
       (material/grey-500 "#9e9e9e")
       (material/grey-600 "#757575")
       (material/grey-700 "#616161")
       (material/grey-800 "#424242")
       (material/grey-900 "#212121")

       (material/inidigo-050  "#e8eaf6")
       (material/inidigo-100  "#c5cae9")
       (material/inidigo-200  "#9fa8da")
       (material/inidigo-300  "#7986cb")
       (material/inidigo-400  "#5c6bc0")
       (material/inidigo-500  "#3f51b5")
       (material/inidigo-600  "#3949ab")
       (material/inidigo-700  "#303f9f")
       (material/inidigo-800  "#283593")
       (material/inidigo-900  "#1a237e")
       (material/inidigo-A100 "#8c9eff")
       (material/inidigo-A200 "#536dfe")
       (material/inidigo-A400 "#3d5afe")
       (material/inidigo-A700 "#304ffe")

       (material/light-blue-050  "#e1f5fe")
       (material/light-blue-100  "#b3e5fc")
       (material/light-blue-200  "#81d4fa")
       (material/light-blue-300  "#4fc3f7")
       (material/light-blue-400  "#29b6f6")
       (material/light-blue-500  "#03a9f4")
       (material/light-blue-600  "#039be5")
       (material/light-blue-700  "#0288d1")
       (material/light-blue-800  "#0277bd")
       (material/light-blue-900  "#01579b")
       (material/light-blue-A100 "#80d8ff")
       (material/light-blue-A200 "#40c4ff")
       (material/light-blue-A400 "#00b0ff")
       (material/light-blue-A700 "#0091ea")

       (material/light-green-050  "#f1f8e9")
       (material/light-green-100  "#dcedc8")
       (material/light-green-200  "#c5e1a5")
       (material/light-green-300  "#aed581")
       (material/light-green-400  "#9ccc65")
       (material/light-green-500  "#8bc34a")
       (material/light-green-600  "#7cb342")
       (material/light-green-700  "#689f38")
       (material/light-green-800  "#558b2f")
       (material/light-green-900  "#33691e")
       (material/light-green-A100 "#ccff90")
       (material/light-green-A200 "#b2ff59")
       (material/light-green-A400 "#76ff03")
       (material/light-green-A700 "#64dd17")

       (material/lime-050  "#f9fbe7")
       (material/lime-100  "#f0f4c3")
       (material/lime-200  "#e6ee9c")
       (material/lime-300  "#dce775")
       (material/lime-400  "#d4e157")
       (material/lime-500  "#cddc39")
       (material/lime-600  "#c0ca33")
       (material/lime-700  "#afb42b")
       (material/lime-800  "#9e9d24")
       (material/lime-900  "#827717")
       (material/lime-A100 "#f4ff81")
       (material/lime-A200 "#eeff41")
       (material/lime-A400 "#c6ff00")
       (material/lime-A700 "#aeea00")

       (material/orange-050  "#fff3e0")
       (material/orange-100  "#ffe0b2")
       (material/orange-200  "#ffcc80")
       (material/orange-300  "#ffb74d")
       (material/orange-400  "#ffa726")
       (material/orange-500  "#ff9800")
       (material/orange-600  "#fb8c00")
       (material/orange-700  "#f57c00")
       (material/orange-800  "#ef6c00")
       (material/orange-900  "#e65100")
       (material/orange-A100 "#ffd180")
       (material/orange-A200 "#ffab40")
       (material/orange-A400 "#ff9100")
       (material/orange-A700 "#ff6d00")

       (material/pink-050  "#fce4ec")
       (material/pink-100  "#f8bbd0")
       (material/pink-200  "#f48fb1")
       (material/pink-300  "#f06292")
       (material/pink-400  "#ec407a")
       (material/pink-500  "#e91e63")
       (material/pink-600  "#d81b60")
       (material/pink-700  "#c2185b")
       (material/pink-800  "#ad1457")
       (material/pink-900  "#880e4f")
       (material/pink-A100 "#ff80ab")
       (material/pink-A200 "#ff4081")
       (material/pink-A400 "#f50057")
       (material/pink-A700 "#c51162")

       (material/purple-050  "#f3e5f5")
       (material/purple-100  "#e1bee7")
       (material/purple-200  "#ce93d8")
       (material/purple-300  "#ba68c8")
       (material/purple-400  "#ab47bc")
       (material/purple-500  "#9c27b0")
       (material/purple-600  "#8e24aa")
       (material/purple-700  "#7b1fa2")
       (material/purple-800  "#6a1b9a")
       (material/purple-900  "#4a148c")
       (material/purple-A100 "#ea80fc")
       (material/purple-A200 "#e040fb")
       (material/purple-A400 "#d500f9")
       (material/purple-A700 "#aa00ff")

       (material/red-050  "#ffebee")
       (material/red-100  "#ffcdd2")
       (material/red-200  "#ef9a9a")
       (material/red-300  "#e57373")
       (material/red-400  "#ef5350")
       (material/red-500  "#f44336")
       (material/red-600  "#e53935")
       (material/red-700  "#d32f2f")
       (material/red-800  "#c62828")
       (material/red-900  "#b71c1c")
       (material/red-A100 "#ff8a80")
       (material/red-A200 "#ff5252")
       (material/red-A400 "#ff1744")
       (material/red-A700 "#d50000")

       (material/teal-050  "#e0f2f1")
       (material/teal-100  "#b2dfdb")
       (material/teal-200  "#80cbc4")
       (material/teal-300  "#4db6ac")
       (material/teal-400  "#26a69a")
       (material/teal-500  "#009688")
       (material/teal-600  "#00897b")
       (material/teal-700  "#00796b")
       (material/teal-800  "#00695c")
       (material/teal-900  "#004d40")
       (material/teal-A100 "#a7ffeb")
       (material/teal-A200 "#64ffda")
       (material/teal-A400 "#1de9b6")
       (material/teal-A700 "#00bfa5")

       (material/yellow-050  "#fffde7")
       (material/yellow-100  "#fff9c4")
       (material/yellow-200  "#fff59d")
       (material/yellow-300  "#fff176")
       (material/yellow-400  "#ffee58")
       (material/yellow-500  "#ffeb3b")
       (material/yellow-600  "#fdd835")
       (material/yellow-700  "#fbc02d")
       (material/yellow-800  "#f9a825")
       (material/yellow-900  "#f57f17")
       (material/yellow-A100 "#ffff8d")
       (material/yellow-A200 "#ffff00")
       (material/yellow-A400 "#ffea00")
       (material/yellow-A700 "#ffd600")

       (materialuicolors/amber       "#ffc107")
       (materialuicolors/blue        "#2196f3")
       (materialuicolors/blue-grey   "#607d8b")
       (materialuicolors/brown       "#795548")
       (materialuicolors/cyan        "#00bcd4")
       (materialuicolors/deep-orange "#ff5722")
       (materialuicolors/deep-purple "#673ab7")
       (materialuicolors/green       "#4caf50")
       (materialuicolors/grey        "#9e9e9e")
       (materialuicolors/indigo      "#3f51b5")
       (materialuicolors/light-blue  "#03a9f4")
       (materialuicolors/light-green "#8bc34a")
       (materialuicolors/lime        "#cddc39")
       (materialuicolors/orange      "#ff9800")
       (materialuicolors/pink        "#e91e63")
       (materialuicolors/purple      "#9c27b0")
       (materialuicolors/red         "#f44336")
       (materialuicolors/teal        "#009688")
       (materialuicolors/yellow      "#ffeb3b")

       (nord/aurora-nord-11     "#bf616a")
       (nord/aurora-nord-12     "#d08770")
       (nord/aurora-nord-13     "#ebcb8b")
       (nord/aurora-nord-14     "#a3be8c")
       (nord/aurora-nord-15     "#b48ead")
       (nord/frost-nord-10      "#5e81ac")
       (nord/frost-nord-7       "#8fbcbb")
       (nord/frost-nord-8       "#88c0d0")
       (nord/frost-nord-9       "#81a1c1")
       (nord/polar-night-nord-0 "#2e3440")
       (nord/polar-night-nord-1 "#3b4252")
       (nord/polar-night-nord-2 "#434c5e")
       (nord/polar-night-nord-3 "#4c566a")
       (nord/snow-storm-nord-4  "#d8dee9")
       (nord/snow-storm-nord-5  "#d8dee9")
       (nord/snow-storm-nord-6  "#eceff4")

       (qualitative/aqua-20    "#71cddd")
       (qualitative/blue-40    "#5392ff")
       (qualitative/gold-20    "#ffb000")
       (qualitative/green-30   "#34bc6e")
       (qualitative/indigo-40  "#9b82f3")
       (qualitative/lime-20    "#95d13c")
       (qualitative/magenta-40 "#ff509e")
       (qualitative/peach-30   "#fe8500")

       (russian/apple-valley            "#ea8685")
       (russian/biscay                  "#303952")
       (russian/blue-curacao            "#3dc1d3")
       (russian/brewed-mustard          "#e77f67")
       (russian/cornflower              "#546de5")
       (russian/creamy-peach            "#f3a683")
       (russian/deep-rose               "#c44569")
       (russian/flamigo-pink            "#f78fb3")
       (russian/old-geranium            "#cf6a87")
       (russian/pencil-lead             "#596275")
       (russian/porcelain-rose          "#e66767")
       (russian/purple-corallite        "#574b90")
       (russian/purple-mountain-majesty "#786fa6")
       (russian/rogue-pink              "#f8a5c2")
       (russian/rosy-highlight          "#f7d794")
       (russian/sawtooth-aak            "#f19066")
       (russian/soft-blue               "#778beb")
       (russian/squeaky                 "#63cdda")
       (russian/summertime              "#f5cd79")
       (russian/tigerlilly              "#e15f41")

       (spanish/alameda-ochre       "#cc8e35")
       (spanish/c64-purple          "#706fd3")
       (spanish/celestial-green     "#33d9b2")
       (spanish/chilean-fire        "#cd6133")
       (spanish/crocodile-tooth     "#d1ccc0")
       (spanish/desert              "#ccae62")
       (spanish/devil-blue          "#227093")
       (spanish/eye-of-newt         "#b33939")
       (spanish/fluorescent-red     "#ff5252")
       (spanish/grey-porcelain      "#84817a")
       (spanish/hot-stone           "#aaa69d")
       (spanish/jacksons-purple     "#40407a")
       (spanish/liberty             "#474787")
       (spanish/lucky-point         "#2c2c54")
       (spanish/mandarin-sorbet     "#ffb142")
       (spanish/palm-springs-splash "#218c74")
       (spanish/spiced-butternut    "#ffda79")
       (spanish/summer-sky          "#34ace0")
       (spanish/swan-white          "#f7f1e3")
       (spanish/synthetic-pumpkin   "#ff793f")

       (solar/bg-base0    "#839496")
       (solar/bg-base1    "#93a1a1")
       (solar/bg-base2    "#eee8d5")
       (solar/bg-base3    "#fdf6e3")
       (solar/fg-base00   "#657b83")
       (solar/fg-base01   "#586e75")
       (solar/fg-base02   "#073642")
       (solar/fg-base03   "#002b36")
       (solar/fg-blue     "#268bd2")
       (solar/fg-cyan     "#2aa198")
       (solar/fg-green    "#859900")
       (solar/fg-magenta  "#d33682")
       (solar/fg-orange   "#cb4b16")
       (solar/fg-red      "#dc322f")
       (solar/fg-violet   "#6c71c4")
       (solar/fg-yellow   "#b58900")

       (srcsery/black          "#1c1b19")
       (srcsery/blue           "#2c78bf")
       (srcsery/bright-black   "#2d2c29")
       (srcsery/bright-blue    "#68a8e4")
       (srcsery/bright-cyan    "#53fde9")
       (srcsery/bright-green   "#98bc37")
       (srcsery/bright-magenta "#ff5c8f")
       (srcsery/bright-red     "#f75341")
       (srcsery/bright-white   "#fce8c3")
       (srcsery/bright-yellow  "#fed06e")
       (srcsery/cyan           "#0aaeb3")
       (srcsery/green          "#519f50")
       (srcsery/magenta        "#e02c6d")
       (srcsery/red            "#ef2f27")
       (srcsery/white          "#918175")
       (srcsery/yellow         "#fbb829")

       (swedish/black-pearl          "#1e272e")
       (swedish/chrome-yellow        "#ffa801")
       (swedish/dark-periwinkle      "#575fcf")
       (swedish/free-speech-blue     "#3c40c6")
       (swedish/fresh-turquoise      "#34e7e4")
       (swedish/good-night           "#485460")
       (swedish/green-teal           "#05c46b")
       (swedish/highlighter-pink     "#ef5777")
       (swedish/hint-of-elusive-blue "#d2dae2")
       (swedish/jade-dust            "#00d8d6")
       (swedish/london-square        "#808e9b")
       (swedish/megaman              "#4bcffa")
       (swedish/minty-green          "#0be881")
       (swedish/nârenji-orange       "#ffc048")
       (swedish/red-orange           "#ff3f34")
       (swedish/sizzling-red         "#f53b57")
       (swedish/spiro-disco-ball     "#0fbcf9")
       (swedish/sunset-orange        "#ff5e57")
       (swedish/vibrant-yellow       "#ffd32a")
       (swedish/yriel-yellow         "#ffdd59")

       (turkish/baltic-sea       "#3d3d3d")
       (turkish/bright-lilac     "#cd84f1")
       (turkish/dorn-yellow      "#fff200")
       (turkish/electric-blue    "#7efff5")
       (turkish/hammam-blue      "#67e6dc")
       (turkish/light-indigo     "#7158e2")
       (turkish/light-purple     "#c56cf0")
       (turkish/light-red        "#ff4d4d")
       (turkish/light-slate-blue "#7d5fff")
       (turkish/mandarin-sorbet  "#ffaf40")
       (turkish/neon-blue        "#18dcff")
       (turkish/pretty-please    "#ffcccc")
       (turkish/radiant-yellow   "#ff9f1a")
       (turkish/red-orange       "#ff3838")
       (turkish/shadowed-steel   "#4b4b4b")
       (turkish/spiro-disco-ball "#17c0eb")
       (turkish/unmellow-yellow  "#fffa65")
       (turkish/weird-green      "#3ae374")
       (turkish/wintergreen      "#32ff7e")
       (turkish/young-salmon     "#ffb8b8")


       (mint-y/green "#8fa876")
       (mint-x/black "#2f2f2f")
       (mint-x/white "#cccccc")

       (ubuntu/shell-background "#2d0922")

       ;; theme colors

       (fontaine/fg-black      x11/black)
       (fontaine/fg-brown      x11/brown4)
       (fontaine/fg-red        x11/red2)
       (fontaine/fg-orange     solar/fg-orange)
       (fontaine/fg-yellow     nil)
       (fontaine/fg-green      dutch/turkish-aqua)

       (fontaine/black         x11/black)
       (fontaine/black-ui      mint-x/black)

       (fontaine/blue          dutch/merchant-marine-blue)
       (fontaine/blue-1        french/azraq-blue)
       (fontaine/blue-bright   turkish/neon-blue)
       (fontaine/blue-dark     dutch/20000-leagues-under-the-sea)
       (fontaine/blue-deep     "#00bfff")
       (fontaine/blue-light    swedish/free-speech-blue)
       (fontaine/blue-purple   aussie/blurple)

       (fontaine/brown         "#8b4513")

       (fontaine/cyan-dark     material/cyan-900)

       (fontaine/gray          flat/asbestos)
       (fontaine/gray-medium   russian/pencil-lead)
       (fontaine/gray-light    "#a6a6a6")
       (fontaine/gray-ui-1     ibm/cool-gray-70)
       (fontaine/gray-ui-2     ibm/cool-gray-60)
       (fontaine/gray-ui-3     ibm/cool-gray-50)

       (fontaine/green         mint-y/green)
       (fontaine/green-1       aussie/pure-apple)
       (fontaine/green-dark    ibm/green-60)
       (fontaine/green-ui-1    material/light-green-600)
       (fontaine/green-ui-2    material/light-green-600)
       (fontaine/green-ui-3    material/light-green-400)

       (fontaine/green-blue    aussie/greenland-green)

       (fontaine/orange        material/orange-900)
       (fontaine/orange-1      aussie/quince-jelly)
       (fontaine/orange-2      ibm/orange-50)
       (fontaine/orange-dark   solar/fg-orange)
       (fontaine/orange-yellow german/nyc-taxi)

       (fontaine/pink          indian/saquatch-socks)
       (fontaine/pink-1        aussie/carmine-pink)

       (fontaine/purple        canadian/nasu-purple)
       (fontaine/purple-red    indian/magenta-purple)

       (fontaine/red           solar/fg-red)
       (fontaine/red-1         french/mandarin-red)
       (fontaine/red-bright    "red")
       (fontaine/red-dark      "firebrick")

       (fontaine/turquoise     swedish/fresh-turquoise)

       (fontaine/violet-red    "#d02090")

       (fontaine/white         "white")
       (fontaine/white-ui      mint-x/white)

       (fontaine/yellow        turkish/dorn-yellow)

       ;; theme elements

       (fontaine/array                  fontaine/purple)
       (fontaine/box                    fontaine/white)
       (fontaine/builtin                fontaine/cyan-dark)
       (fontaine/comment                fontaine/red-dark)
       (fontaine/constant               fontaine/green-dark)
       (fontaine/current-line           fontaine/white)
       (fontaine/cursor                 fontaine/black)
       (fontaine/declare                fontaine/gray)
       (fontaine/error                  fontaine/red-bright)
       (fontaine/function               fontaine/blue-light)
       (fontaine/hash                   fontaine/pink-1)
       (fontaine/keyword                fontaine/black)
       (fontaine/line-number            fontaine/gray-medium)
       (fontaine/match                  fontaine/blue-bright)
       (fontaine/mode-line-active-bg    fontaine/black-ui)
       (fontaine/mode-line-active-fg    fontaine/white-ui)
       (fontaine/mode-line-inactive-bg  fontaine/black-ui)
       (fontaine/mode-line-inactive-fg  fontaine/white-ui)
       (fontaine/non-over               fontaine/gray-medium)
       (fontaine/operator               fontaine/orange-dark)
       (fontaine/paren-match            fontaine/turquoise)
       (fontaine/paren-mismatch-bg      fontaine/yellow)
       (fontaine/paren-mismatch-fg      fontaine/red-bright)
       (fontaine/paren-no-match-bg      fontaine/red-bright)
       (fontaine/paren-no-match-fg      fontaine/yellow)
       (fontaine/powerline-active1-bg   fontaine/mode-line-active-bg)
       (fontaine/powerline-active1-fg   fontaine/mode-line-active-fg)
       (fontaine/powerline-active2-bg   fontaine/green-ui-2)
       (fontaine/powerline-active2-fg   fontaine/black)
       (fontaine/powerline-active3-bg   fontaine/green-ui-3)
       (fontaine/powerline-active3-fg   fontaine/black)
       (fontaine/powerline-inactive1-bg fontaine/mode-line-inactive-bg)
       (fontaine/powerline-inactive1-fg fontaine/mode-line-inactive-fg)
       (fontaine/powerline-inactive2-bg fontaine/gray-ui-2)
       (fontaine/powerline-inactive2-fg fontaine/white-ui)
       (fontaine/powerline-inactive3-bg fontaine/gray-ui-3)
       (fontaine/powerline-inactive3-fg fontaine/white-ui)
       (fontaine/prompt                 fontaine/red)
       (fontaine/rainbow-1              fontaine/purple-red)
       (fontaine/rainbow-2              fontaine/violet-red)
       (fontaine/rainbow-3              fontaine/blue-purple)
       (fontaine/rainbow-4              fontaine/blue-1)
       (fontaine/rainbow-5              fontaine/green-blue)
       (fontaine/rainbow-6              fontaine/green-1)
       (fontaine/rainbow-7              fontaine/orange-1)
       (fontaine/rainbow-8              fontaine/orange-2)
       (fontaine/rainbow-9              fontaine/red-1)
       (fontaine/region                 fontaine/yellow)
       (fontaine/secondary              fontaine/orange-yellow)
       (fontaine/separator              fontaine/gray-light)
       (fontaine/string                 fontaine/brown)
       (fontaine/success                fontaine/green-dark)
       (fontaine/tabbar-default-bg      fontaine/black-ui)
       (fontaine/tabbar-default-fg      fontaine/white-ui)
       ;; (fontaine/tabbar-modified-bg     fontaine/red-bright)
       ;; (fontaine/tabbar-modified-fg     fontaine/white)
       (fontaine/tabbar-selected-bg     "nil")
       (fontaine/tabbar-selected-fg     fontaine/black)
       (fontaine/tabbar-unselected-bg   ibm/cool-gray-70)
       (fontaine/tabbar-unselected-fg   fontaine/white-ui)
       (fontaine/tabbar-modified-s-fg   fontaine/red-bright)
       (fontaine/tabbar-modified-bg     fontaine/red-dark)
       (fontaine/tabbar-modified-fg     fontaine/white-ui)
       (fontaine/type                   fontaine/blue-dark)
       (fontaine/variable               fontaine/blue)
       (fontaine/volatile-highlight     fontaine/blue-deep)
       (fontaine/warning                fontaine/orange)
       )

;; 6 matches for "set-face-attribute" in buffer: *scratch*
;;      48:(set-face-attribute 'tabbar-default nil           fontaine/tabbar-default-bg    fontaine/tabbar-default-fg
;;      55:(set-face-attribute 'tabbar-unselected nil        fontaine/tabbar-unselected-bg fontaine/tabbar-unselected-fg
;;      60:(set-face-attribute 'tabbar-modified nil          fontaine/tabbar-modified-bg   fontaine/tabbar-modified-fg
;;      66:(set-face-attribute 'tabbar-selected nil                                        fontaine/tabbar-selected-fg
;;      72:(set-face-attribute 'tabbar-selected-modified nil                               fontaine/tabbar-modified-s-fg
;;      78:(set-face-attribute 'tabbar-button nil
  ;; (defface tabbar-unselected `((t (:inherit fontaine/variable-pitch :background ,fontaine/tabbar-unselected-bg :foreground ,fontaine/tabbar-unselected-fg))) "Temp face." :group 'font-lock-faces)

  ;; (defface tabbar-selected   `((t (:inherit fontaine/variable-pitch :background ,fontaine/tabbar-selected-bg   :foreground ,fontaine/tabbar-selected-fg :weight bold))) "Temp face." :group 'font-lock-faces)

  ;; (defface tabbar-selected-modified   `((t (:inherit tabbar-selected   :foreground ,fontaine/tabbar-modified-s-fg)))   "Temp face." :group 'font-lock-faces)
  ;; (defface tabbar-unselected-modified `((t (:inherit tabbar-unselected :foreground ,fontaine/tabbar-modified-u-fg :background ,fontaine/tabbar-modified-u-bg))) "Temp face." :group 'font-lock-faces)

  (defface fontaine/mode-line-base '((t (:family "DejaVu Sans" :box (:line-width 1 :color "gray50")))) "Temp face." :group 'font-lock-faces)
  (defface fontaine/variable-pitch '((t (:inherit variable-pitch :height 0.8))) "Temp face." :group 'font-lock-faces)

  (defface tabbar-default           `((t (:background ,fontaine/tabbar-default-bg :foreground ,fontaine/tabbar-default-fg))) "Temp face." :group 'font-lock-faces)
  (defface tabbar-unselected        `((t (:inherit fontaine/variable-pitch :foreground ,fontaine/tabbar-unselected-fg :background ,fontaine/tabbar-unselected-bg))) "Temp face." :group 'font-lock-faces)
  (defface tabbar-modified          `((t (:inherit tabbar-unselected       :foreground ,fontaine/tabbar-modified-fg   :background ,fontaine/tabbar-modified-bg))) "Temp face." :group 'font-lock-faces)
  (defface tabbar-selected          `((t (:inherit fontaine/variable-pitch :foreground ,fontaine/tabbar-selected-fg :background "nil" :weight bold))) "Temp face." :group 'font-lock-faces)
  (defface tabbar-selected-modified `((t (:inherit tabbar-selected         :foreground ,fontaine/tabbar-modified-s-fg))) "Temp face." :group 'font-lock-faces)
  (defface tabbar-button            `((t (:inherit tabbar-unselected))) "Temp face." :group 'font-lock-faces)

  (custom-theme-set-faces
   `fontaine
   `(default             ((t (:family ,font-family :height 120 :width normal))))
   ;;
   `(cursor              ((t (:background ,fontaine/cursor))))
   `(region              ((t (:background ,fontaine/region))))
   `(secondary-selection ((t (:background ,fontaine/secondary))))
   ;;
   `(fringe              ((t (:background nil))))
   ;;
   `(error   ((t (:foreground ,fontaine/error   :weight bold))))
   `(success ((t (:foreground ,fontaine/success :weight bold))))
   `(warning ((t (:foreground ,fontaine/warning :weight bold))))
   ;;
   `(mode-line           ((t (:inherit fontaine/mode-line-base :background ,fontaine/mode-line-active-bg   :foreground ,fontaine/mode-line-active-fg))))
   `(mode-line-inactive  ((t (:inherit fontaine/mode-line-base :background ,fontaine/mode-line-inactive-bg :foreground ,fontaine/mode-line-inactive-fg))))

   `(powerline-active1   ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-active1-bg :foreground ,fontaine/powerline-active1-fg :weight bold))))
   `(powerline-active2   ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-active2-bg :foreground ,fontaine/powerline-active2-fg))))
   `(powerline-active3   ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-active3-bg :foreground ,fontaine/powerline-active3-fg))))

   `(powerline-inactive1 ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-inactive1-bg :foreground ,fontaine/powerline-inactive1-fg :weight bold))))
   `(powerline-inactive2 ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-inactive2-bg :foreground ,fontaine/powerline-inactive2-fg))))
   `(powerline-inactive3 ((t (:inherit fontaine/mode-line-base :background ,fontaine/powerline-inactive3-bg :foreground ,fontaine/powerline-inactive3-fg))))


   `(anzu-mode-line      ((t (:inherit minibuffer-prompt :foreground ,fontaine/match :weight bold))))
   
   ;; `(clips-constant-face             ((t (:foreground ,solar/fg-blue))))
   ;; `(clips-control-face              ((t (:foreground "cyan4"         :weight bold))))
   ;; `(clips-declaration-face          ((t (:foreground "gray40"        :weight bold))))
   ;; `(clips-function-face             ((t (:foreground ,solar/fg-green :weight bold))))
   ;; `(clips-global-variable-face      ((t (:foreground "navy"))))
   ;; `(clips-logical-face              ((t (:foreground ,solar/fg-cyan  :weight bold))))
   ;; `(clips-object-match-face         ((t (:foreground "purple"        :weight bold))))
   ;; `(clips-variable-face             ((t (:foreground "royalblue"))))
   ;; `(clips-verb-face                 ((t (:foreground "green4"        :weight bold))))

   ;; `(clips-log-activate-face         ((t (:foreground ,solar/fg-magenta :weight bold))))
   ;; `(clips-log-deactivate-face       ((t (:foreground ,solar/fg-magenta))))
   ;; `(clips-log-make-instance-face    ((t (:foreground ,solar/fg-blue :weight bold))))
   ;; `(clips-log-unmake-instance-face  ((t (:foreground ,solar/fg-blue))))
   ;; `(clips-log-fire-face             ((t (:foreground "blue3" :weight bold))))
   ;; `(clips-log-assert-fact-face      ((t (:foreground ,solar/fg-cyan :weight bold))))
   ;; `(clips-log-retract-fact-face     ((t (:foreground ,solar/fg-cyan))))
   ;; `(clips-log-error-face            ((t (:foreground ,fontaine/error1 :weight bold))))
   ;; `(clips-log-fatal-face            ((t (:foreground ,fontaine/error1 :background ,fontaine/ :weight bold))))
   ;; `(clips-log-pass-face             ((t (:foreground "ForestGreen" :weight bold))))

   `(comint-highlight-prompt         ((t (:foreground ,fontaine/prompt :weight bold))))

   `(compilation-column-number       ((t (:weight bold))))
   `(compilation-line-number         ((t (:weight bold))))
   `(compilation-warning             ((t (:foreground ,fontaine/warning :weight bold))))

   `(cperl-array-face                ((t (:foreground ,fontaine/array    :weight bold))))
   `(cperl-hash-face                 ((t (:foreground ,fontaine/hash     :weight bold))))
   `(cperl-nonoverridable-face       ((t (:foreground ,fontaine/non-over :weight bold))))

   `(font-lock-comment-face          ((t (:foreground ,fontaine/comment :slant italic))))
   `(font-lock-doc-face              ((t (:foreground ,fontaine/comment :slant italic :weight bold))))

   `(font-lock-string-face           ((t (:foreground ,fontaine/string :slant italic))))
   ;; `(font-lock-doc-string-face       ((t (:foreground ,fontaine/string :slant italic))))

   `(font-lock-builtin-face          ((t (:foreground ,fontaine/builtin    :weight bold))))
   `(font-lock-constant-face         ((t (:foreground ,fontaine/constant   :weight bold))))
   `(font-lock-function-name-face    ((t (:foreground ,fontaine/function   :weight bold))))
   `(font-lock-keyword-face          ((t (:foreground ,fontaine/keyword    :weight bold))))
   `(font-lock-type-face             ((t (:foreground ,fontaine/type       :weight bold))))
   `(font-lock-variable-name-face    ((t (:foreground ,fontaine/variable   :weight bold))))
   `(font-lock-warning-face          ((t (:foreground ,fontaine/warning    :weight bold))))

   `(git-gutter:added                ((t (:foreground ,solar/fg-green      :weight bold))))
   `(git-gutter:deleted              ((t (:foreground ,fontaine/red        :weight bold))))
   `(git-gutter:modified             ((t (:foreground ,fontaine/blue       :weight bold))))

   ;; `(hes-escape-backslash-face ((t (:weight bold))))
   ;; `(hes-escape-face           ((t (:weight bold))))
   ;; `(hes-escape-sequence-face  ((t (:weight bold))))

   `(highlight ((t (:background ,fontaine/match))))

   ;; `(highlight-operators-face ((t (:foreground ,fontaine/operator :weight bold))))

   `(hl-line ((t (:background ,fontaine/current-line))))

   `(isearch ((t (:background ,fontaine/match))))

   `(line-number              ((t (:foreground ,fontaine/line-number))))
   `(line-number-current-line ((t (:foreground ,fontaine/line-number :weight bold))))

   `(match ((t (:background ,fontaine/match))))

   `(paren-face-match    ((t (:background ,fontaine/paren-match))))
   `(paren-face-mismatch ((t (:background ,fontaine/paren-mismatch-bg :foreground ,fontaine/paren-mismatch-fg))))
   `(paren-face-no-match ((t (:background ,fontaine/paren-no-match-bg :foreground ,fontaine/paren-no-match-fg))))

   `(rainbow-delimiters-base-face    ((t (:inherit unspecified :weight bold))))
   `(rainbow-delimiters-depth-1-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-1))))
   `(rainbow-delimiters-depth-2-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-2))))
   `(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-3))))
   `(rainbow-delimiters-depth-4-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-4))))
   `(rainbow-delimiters-depth-5-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-5))))
   `(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-6))))
   `(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-7))))
   `(rainbow-delimiters-depth-8-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-8))))
   `(rainbow-delimiters-depth-9-face ((t (:inherit rainbow-delimiters-base-face :foreground ,fontaine/rainbow-9))))
   ;; `(sh-heredoc                      ((t (:foreground ,fontaine/string))))
   ;; `(sh-heredoc-face                 ((t (:foreground ,fontaine/comment))))
   ;; `(sh-quoted-exec                  ((t (:foreground "magenta3" :slant italic)))) ;; !!!

   `(vhl/default-face ((t (:background ,fontaine/volatile-highlight))))

   ;; `(web-mode-json-context-face      ((t (:foreground ,material/fg-pink-500 :weight bold)))) ;; !!!
   `(web-mode-json-key-face          ((t (:weight bold))))
   ))
 ;;
(message "Loading fontaine-theme...done")
(provide-theme 'fontaine)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; fontaine-theme.el ends here
;; rainbow ((((((((()))))))))
