#!/usr/bin/perl -w    # -*-Perl-*-

#         Copyright © 2022-2022 Tom Fontaine

# Title:  pantone
# Date:   21-Feb-2022

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software",
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Except as contained in this notice, the name(s of the above copyright
# holders shall not be used in advertising or otherwise to promote the sale,
# use or other dealings in this Software without prior written authorization.

# The software is provided "As Is", without warranty of any kind, express or
# implied, including but not limited to the warranties of merchantability,
# fitness for a particular purpose and noninfringement. In no event shall
# the authors or copyright holders be liable for any claim, damages or other
# liability, whether in an action of contract, tort or otherwise, arising
# from, out of or in connection with the software or the use or other
# dealings in the software.

#
# Purpose:
#
# Arguments:
#
# Revision:
#
use strict;
use v5.10;

use File::IO;

use constant _ME_ => $0 =~ m=([^/]+)$=;

my $io = File::IO->new(path => "$ENV{HOME}/ide/elisp/themes/colors/pantone.el",chomp => 1,newline => 1);

$io->get();

my @text;

my $flag = 0;

my ($colorHex,$colorName);

for(@{$io->contents})
{
  $flag = 1 if /^hex/i;

  if($flag == 0)
  {
    push @text,$_;

    next;
  }
  if(/^hex#: ([[:xdigit:]]+)/i)
  {
    $colorHex = join '','"#',lc($1),'"';
  }
  elsif(/^[^:]+$/)
  {
    s/ /-/g;
    s/[*\']//g;

    $colorName = lc $_;

    push @text,join '','(defconst pantone/',$colorName,' ',$colorHex,')';
  }
}
$io->put(contents => \@text);
