;;; social.el --- color definitions -*-Emacs-Lisp-*-

;;         Copyright © 2020-2024  Tom Fontaine

(defconst social/behance     "#E4405F")
(defconst social/blogger     "#F57D00")
(defconst social/dribble     "#EA4C89")
(defconst social/dropbox     "#0061FF")
(defconst social/facebook    "#1877F2")
(defconst social/flickr      "#FF0084")
(defconst social/foursquare  "#F94877")
(defconst social/hackernews  "#FF6600")
(defconst social/instagram   "#E4405F")
(defconst social/line        "#00C300")
(defconst social/linkedin    "#0A66C2")
(defconst social/medium      "#02B875")
(defconst social/messenger   "#0099FF")
(defconst social/pinterest   "#BD081C")
(defconst social/producthunt "#DA552F")
(defconst social/quora       "#B92B27")
(defconst social/reddit      "#FF5700")
(defconst social/skype       "#00AFF0")
(defconst social/slack       "#3AAF85")
(defconst social/slideshare  "#0077B5")
(defconst social/snapchat    "#FFFC00")
(defconst social/soundcloud  "#FF3300")
(defconst social/tiktok      "#EE1D51")
(defconst social/tumblr      "#34465D")
(defconst social/twitter     "#1DA1F2")
(defconst social/vimeo       "#1AB7EA")
(defconst social/vine        "#00B489")
(defconst social/vk          "#4C75A3")
(defconst social/wechat      "#09B83E")
(defconst social/weibo       "#DF2029")
(defconst social/whatsapp    "#25D366")
(defconst social/wordpress   "#21759B")
(defconst social/yahoo       "#410093")
(defconst social/yelp        "#AF0606")
(defconst social/youtube     "#CD201F")

;;; social.el ends here
